In [1]:
#import dependencies

%matplotlib inline
import matplotlib.pyplot as plt
import pandas as pd
from pprint import pprint
from pymongo import MongoClient

In [2]:
data_path="../Resources/"

In [7]:
# pop_df = pd.read_csv(data_path+"nst-est2019-popchg2010_2019.csv",skiprows =range(1,6))

In [8]:
# pop_df

In [9]:
# pop_df=pop_df.iloc[:,4:16]

In [10]:
# pop_df.head()

In [11]:
# pop_df.columns

In [12]:
# #rename the columns
# pop_df = pop_df.rename(columns={"NAME":"State","ESTIMATESBASE2010":"EST2010","POPESTIMATE2010":"2010", 
#                                 'POPESTIMATE2011': '2011', 'POPESTIMATE2012': '2012',
#                                'POPESTIMATE2013' : '2013', 'POPESTIMATE2014': '2014', 
#                                 'POPESTIMATE2015' : '2015', 'POPESTIMATE2016' :'2016', 
#                                 'POPESTIMATE2017' :'2017', 'POPESTIMATE2018': '2018','POPESTIMATE2019': '2019'})

In [13]:
# # convert the data change columns to rows so our data is linear
# pop_df = pop_df.melt(id_vars =["State"], var_name ="Year",value_name = "Population")
# pop_df

In [14]:
# us_pop = pop_df.groupby(['Year']).sum().reset_index()
# us_pop

In [15]:
# #slicing the data in the desired format
# pop_df1=pop_df.iloc[:,4:16]
# #df1 = df.iloc[:, 0:2]

In [16]:
# pop_df1.head()

In [17]:
energy_cons = pd.read_excel(data_path+"Table_1.3_Primary_Energy_Consumption_by_Source.xlsx",'Annual Data',skiprows=range(0,10))

In [18]:
energy_cons

,Annual Total,Coal Consumption,Natural Gas Consumption (Excluding Supplemental Gaseous Fuels),Petroleum Consumption (Excluding Biofuels),Total Fossil Fuels Consumption,Nuclear Electric Power Consumption,Hydroelectric Power Consumption,Geothermal Energy Consumption,Solar Energy Consumption,Wind Energy Consumption,Biomass Energy Consumption,Total Renewable Energy Consumption,Total Primary Energy Consumption
0,NaN,(Quadrillion Btu),(Quadrillion Btu),(Quadrillion Btu),(Quadrillion Btu),(Quadrillion Btu),(Quadrillion Btu),(Quadrillion Btu),(Quadrillion Btu),(Quadrillion Btu),(Quadrillion Btu),(Quadrillion Btu),(Quadrillion Btu)
1,1949.0,11.9809,5.14514,11.869,28.9884,0,1.42472,Not Available,Not Available,Not Available,1.54926,2.97398,31.9678
2,1950.0,12.3471,5.96837,13.2983,31.6148,0,1.41541,Not Available,Not Available,Not Available,1.56231,2.97772,34.5986
3,1951.0,12.553,7.04852,14.4077,33.9877,0,1.42379,Not Available,Not Available,Not Available,1.53467,2.95846,36.9537
4,1952.0,11.3065,7.54962,14.9339,33.7781,0,1.46581,Not Available,Not Available,Not Available,1.47437,2.94018,36.726
...,...,...,...,...,...,...,...,...,...,...,...,...,...
67,2015.0,15.5489,28.1911,35.3681,79.0903,8.33689,2.32118,0.211836,0.426867,1.77731,4.98336,9.72054,97.3752
68,2016.0,14.2259,28.4004,35.7119,78.319,8.42675,2.47244,0.209604,0.570368,2.09559,5.01452,10.3625,97.3352
69,2017.0,13.8375,28.0551,36.0432,77.9071,8.41897,2.76697,0.210233,0.777084,2.34289,4.97934,11.0765,97.5947
70,2018.0,13.2515,31.1534,36.8918,81.2711,8.43807,2.66314,0.208865,0.915513,2.48236,5.0311,11.301,101.162
71,2019.0,11.3155,32.1958,36.8664,80.3566,8.45185,2.56323,0.201269,1.01801,2.62585,4.92381,11.3322,100.274

In [19]:
energy_cons = energy_cons.rename(columns={'Annual Total':'Year', 'Coal Consumption':'Coal_Consumption',
       'Natural Gas Consumption (Excluding Supplemental Gaseous Fuels)':'Gas_Consumption',
       'Petroleum Consumption (Excluding Biofuels)':"Petro_Consumption",
       'Total Fossil Fuels Consumption':'Fossil_Consumption', 'Nuclear Electric Power Consumption':'Electric_consumption',
       'Hydroelectric Power Consumption':'Hydro_Consumption', 'Geothermal Energy Consumption':'Geo_Consumption',
       'Solar Energy Consumption':'Solar_Consumption', 'Wind Energy Consumption':'Wind_Consumption',
       'Biomass Energy Consumption':'Bio_Consumption', 'Total Renewable Energy Consumption':'Total_Renewable_Consumption',
       'Total Primary Energy Consumption':'Total_primary_Cosumption'})

In [20]:
# dropping column with all null values 
energy_cons.dropna(axis =1 ,how = "all", inplace = True)

In [21]:
energy_cons.drop(index=0, inplace=True)

In [22]:
energy_cons.head(60)

,Year,Coal_Consumption,Gas_Consumption,Petro_Consumption,Fossil_Consumption,Electric_consumption,Hydro_Consumption,Geo_Consumption,Solar_Consumption,Wind_Consumption,Bio_Consumption,Total_Renewable_Consumption,Total_primary_Cosumption
1,1949.0,11.9809,5.14514,11.869,28.9884,0,1.42472,Not Available,Not Available,Not Available,1.54926,2.97398,31.9678
2,1950.0,12.3471,5.96837,13.2983,31.6148,0,1.41541,Not Available,Not Available,Not Available,1.56231,2.97772,34.5986
3,1951.0,12.553,7.04852,14.4077,33.9877,0,1.42379,Not Available,Not Available,Not Available,1.53467,2.95846,36.9537
4,1952.0,11.3065,7.54962,14.9339,33.7781,0,1.46581,Not Available,Not Available,Not Available,1.47437,2.94018,36.726
5,1953.0,11.3727,7.90665,15.532,34.8023,0,1.41286,Not Available,Not Available,Not Available,1.4186,2.83146,37.6406
6,1954.0,9.71467,8.3302,15.8133,33.8515,0,1.35977,Not Available,Not Available,Not Available,1.39433,2.7541,36.6135
7,1955.0,11.1673,8.99794,17.2253,37.3804,0,1.35984,Not Available,Not Available,Not Available,1.42414,2.78399,40.1783
8,1956.0,11.3497,9.61397,17.905,38.8557,0,1.43471,Not Available,Not Available,Not Available,1.41587,2.85058,41.7218
9,1957.0,10.8206,10.1908,17.8984,38.8923,0.000112,1.51561,Not Available,Not Available,Not Available,1.33358,2.84919,41.7539
10,1958.0,9.53329,10.6632,18.4912,38.681,0.001915,1.59197,Not Available,Not Available,Not Available,1.32312,2.91509,41.6093
11,1959.0,9.51835,11.7174,19.2799,40.5073,0.002187,1.54846,Not Available,Not Available,Not Available,1.35287,2.90134,43.423
12,1960.0,9.83779,12.3854,19.8735,42.091,0.006026,1.60797,0.000359,Not Available,Not Available,1.31987,2.9282,45.0407
13,1961.0,9.62335,12.9264,20.1693,42.7112,0.019678,1.65646,0.001001,Not Available,Not Available,1.29476,2.95223,45.6908
14,1962.0,9.90645,13.7308,20.9976,44.6294,0.026394,1.81614,0.001061,Not Available,Not Available,1.30024,3.11744,47.775
15,1963.0,10.4125,14.4033,21.6453,46.4537,0.038147,1.77136,0.00176,Not Available,Not Available,1.32332,3.09643,49.5886
16,1964.0,10.9644,15.2879,22.2419,48.4837,0.039819,1.88631,0.002132,Not Available,Not Available,1.3368,3.22525,51.7554
17,1965.0,11.5806,15.7687,23.1839,50.5147,0.043164,2.05908,0.001978,Not Available,Not Available,1.33476,3.39582,53.9532
18,1966.0,12.1431,16.9953,24.3354,53.4488,0.064158,2.06152,0.001958,Not Available,Not Available,1.36898,3.43246,56.9492
19,1967.0,11.9138,17.9448,25.274,55.1172,0.088456,2.34666,0.0033,Not Available,Not Available,1.34025,3.69021,58.8948
20,1968.0,12.3307,19.2097,26.9664,58.4894,0.141534,2.34863,0.004532,Not Available,Not Available,1.41949,3.77266,62.4015
21,1969.0,12.3815,20.678,28.3206,61.344,0.153722,2.64798,0.006422,Not Available,Not Available,1.44049,4.09489,65.5963
22,1970.0,12.2645,21.7947,29.4992,63.5008,0.239347,2.63355,0.005511,Not Available,Not Available,1.43096,4.07002,67.8168
23,1971.0,11.5984,22.4691,30.5387,64.5731,0.412939,2.82415,0.005739,Not Available,Not Available,1.43232,4.26221,69.2603
24,1972.0,12.0769,22.6982,32.9189,67.668,0.583752,2.86387,0.015079,Not Available,Not Available,1.50307,4.38201,72.66
25,1973.0,12.9715,22.5124,34.806,70.2824,0.910177,2.86145,0.020422,Not Available,Not Available,1.52907,4.41094,75.6523
26,1974.0,12.6629,21.7325,33.4206,67.8721,1.27208,3.17658,0.02561,Not Available,Not Available,1.53966,4.74185,73.9293
27,1975.0,12.6628,19.9479,32.6988,65.323,1.8998,3.15461,0.03378,Not Available,Not Available,1.49873,4.68712,71.931
28,1976.0,13.5841,20.3454,35.142,69.0714,2.11112,2.97627,0.037513,Not Available,Not Available,1.71337,4.72715,75.939
29,1977.0,13.9221,19.9305,37.0826,70.9498,2.70176,2.33325,0.037382,Not Available,Not Available,1.83833,4.20897,77.92
30,1978.0,13.7656,20.0004,37.9191,71.8098,3.02413,2.93698,0.030851,Not Available,Not Available,2.03761,5.00544,79.9067
31,1979.0,15.0396,20.6658,37.0755,72.8437,2.77583,2.93069,0.040262,Not Available,Not Available,2.15191,5.12285,80.8118
32,1980.0,15.4228,20.2355,34.159,69.7822,2.73917,2.90014,0.052699,Not Available,Not Available,2.4755,5.42834,78.0211
33,1981.0,15.9075,19.7473,31.8836,67.5225,3.00759,2.75797,0.059437,Not Available,Not Available,2.59628,5.41369,76.0572
34,1982.0,15.3216,18.3562,30.1792,63.8354,3.13115,3.26556,0.050627,Not Available,Not Available,2.66345,5.97964,73.0462
35,1983.0,15.8944,17.2208,29.997,63.0967,3.20255,3.52726,0.06391,Not Available,2.8e-05,2.90441,6.49561,72.9154
36,1984.0,17.0706,18.3936,30.9922,66.445,3.55253,3.38581,0.080811,5.5e-05,6.8e-05,2.97112,6.43786,76.5707
37,1985.0,17.4784,17.7035,30.8665,66.0349,4.07556,2.97019,0.097421,0.000111,6e-05,3.01623,6.08402,76.3341
38,1986.0,17.2604,16.5914,32.1501,65.9852,4.38011,3.07118,0.107677,0.000147,4.4e-05,2.93209,6.11114,76.5989
39,1987.0,18.0085,17.6398,32.8175,68.4744,4.75393,2.63451,0.11227,0.000109,3.7e-05,2.87488,5.62181,79.0082
40,1988.0,18.8463,18.4484,34.1728,71.507,5.58697,2.33426,0.106338,9.4e-05,9e-06,3.01605,5.45675,82.6592
41,1989.0,19.0698,19.6016,34.164,72.8657,5.60216,2.83726,0.161539,0.054466,0.022033,3.15936,6.23466,84.74
42,1990.0,19.1726,19.6033,33.4999,72.2806,6.10435,3.04639,0.170747,0.058768,0.029007,2.73511,6.04002,84.4329
43,1991.0,18.9917,20.033,32.7891,71.8234,6.42213,3.01594,0.177626,0.061623,0.030796,2.7818,6.06778,84.3803
44,1992.0,19.1225,20.7136,33.4677,73.3384,6.47921,2.61744,0.178699,0.06288,0.029863,2.93168,5.82056,85.7249
45,1993.0,19.8351,21.229,33.5876,74.6788,6.4105,2.89161,0.185673,0.06519,0.030987,2.90817,6.08164,87.2659
46,1994.0,19.9095,21.7281,34.4534,76.1493,6.69388,2.68346,0.173464,0.067126,0.03556,3.02753,5.98714,88.9832
47,1995.0,20.0887,22.6711,34.3411,77.162,7.07544,3.20531,0.152057,0.068233,0.03263,3.10114,6.55937,90.9307
48,1996.0,21.0019,23.0846,35.5889,79.6983,7.08667,3.58966,0.163359,0.069134,0.03344,3.15681,7.01239,93.9345
49,1997.0,21.4454,23.2227,36.0651,80.7797,6.59699,3.64046,0.166698,0.068166,0.033581,3.10522,7.01412,94.507
50,1998.0,21.6557,22.8302,36.7198,81.2729,7.06781,3.29705,0.16845,0.067449,0.030853,2.92749,6.4913,94.9202
51,1999.0,21.6225,22.9092,37.7321,82.3216,7.61026,3.26757,0.170921,0.066066,0.045894,2.96329,6.51375,96.5445
52,2000.0,22.5795,23.824,38.1516,84.6204,7.86235,2.81112,0.164364,0.063469,0.057057,3.00823,6.10423,98.7022
53,2001.0,21.9143,22.7726,38.0837,82.7998,8.02885,2.24186,0.164461,0.061674,0.069617,2.62236,5.15997,96.0637
54,2002.0,21.904,23.5101,38.1174,83.5923,8.14543,2.68902,0.171164,0.05998,0.105334,2.70062,5.72612,97.5354
55,2003.0,22.3209,22.8306,38.707,83.9091,7.95962,2.79254,0.173445,0.058432,0.113273,2.80647,5.94416,97.8348
56,2004.0,22.4662,22.9231,40.1393,85.6663,8.22277,2.68847,0.178147,0.058376,0.141664,3.00807,6.07473,100.002
57,2005.0,22.7965,22.5654,40.2166,85.6227,8.16081,2.70294,0.180703,0.057893,0.178088,3.11393,6.23356,100.102
58,2006.0,22.4472,22.2387,39.7305,84.4772,8.21463,2.86903,0.1812,0.060755,0.263738,3.26214,6.63687,99.3915
59,2007.0,22.7495,23.6628,39.3676,85.805,8.45859,2.44639,0.185774,0.065621,0.340503,3.48482,6.52311,100.893
60,2008.0,22.3874,23.843,36.7694,83.0405,8.42649,2.51111,0.192433,0.074207,0.545548,3.85139,7.17469,98.7537

In [23]:
energy_cons['Year'] = energy_cons['Year'].astype(int)

In [24]:
energy_cons.head()

,Year,Coal_Consumption,Gas_Consumption,Petro_Consumption,Fossil_Consumption,Electric_consumption,Hydro_Consumption,Geo_Consumption,Solar_Consumption,Wind_Consumption,Bio_Consumption,Total_Renewable_Consumption,Total_primary_Cosumption
1,1949,11.9809,5.14514,11.869,28.9884,0,1.42472,Not Available,Not Available,Not Available,1.54926,2.97398,31.9678
2,1950,12.3471,5.96837,13.2983,31.6148,0,1.41541,Not Available,Not Available,Not Available,1.56231,2.97772,34.5986
3,1951,12.553,7.04852,14.4077,33.9877,0,1.42379,Not Available,Not Available,Not Available,1.53467,2.95846,36.9537
4,1952,11.3065,7.54962,14.9339,33.7781,0,1.46581,Not Available,Not Available,Not Available,1.47437,2.94018,36.726
5,1953,11.3727,7.90665,15.532,34.8023,0,1.41286,Not Available,Not Available,Not Available,1.4186,2.83146,37.6406

In [25]:
#df = df.apply(lambda x: pd.to_numeric(x, errors='coerce')).fillna(-999999)
#energy_cons1 = energy_cons.apply(lambda x: pd.to_numeric(x, errors='coerce')).fillna(-999999)
#energy_cons1=energy_cons.replace("^\w.*$", "0", regex=True)
#Replace Not available with zeros
energy_cons = energy_cons.replace('Not Available',0)

In [26]:
energy_cons.head()

,Year,Coal_Consumption,Gas_Consumption,Petro_Consumption,Fossil_Consumption,Electric_consumption,Hydro_Consumption,Geo_Consumption,Solar_Consumption,Wind_Consumption,Bio_Consumption,Total_Renewable_Consumption,Total_primary_Cosumption
1,1949,11.980905,5.145142,11.868994,28.988371,0.0,1.424722,0.0,0.0,0.0,1.549262,2.973984,31.967775
2,1950,12.347109,5.968371,13.298283,31.614755,0.0,1.415411,0.0,0.0,0.0,1.562307,2.977718,34.598567
3,1951,12.552996,7.048518,14.407674,33.987736,0.0,1.423795,0.0,0.0,0.0,1.534669,2.958464,36.953661
4,1952,11.306479,7.549621,14.933895,33.778116,0.0,1.465812,0.0,0.0,0.0,1.474369,2.940181,36.726037
5,1953,11.372684,7.906645,15.531959,34.802286,0.0,1.412859,0.0,0.0,0.0,1.418601,2.831460,37.640598

# Energy Production

In [63]:
energy_prod = pd.read_excel(data_path+"Table_10.1_Renewable_Energy_Production_and_Consumption_by_Source.xlsx",'Annual Data',skiprows=range(0,10))

In [64]:
energy_prod

,Annual Total,Wood Energy Production,Biofuels Production,Total Biomass Energy Production,Total Renewable Energy Production,Hydroelectric Power Consumption,Geothermal Energy Consumption,Solar Energy Consumption,Wind Energy Consumption,Wood Energy Consumption,Waste Energy Consumption,Biofuels Consumption,Total Biomass Energy Consumption,Total Renewable Energy Consumption
0,NaN,(Trillion Btu),(Trillion Btu),(Trillion Btu),(Trillion Btu),(Trillion Btu),(Trillion Btu),(Trillion Btu),(Trillion Btu),(Trillion Btu),(Trillion Btu),(Trillion Btu),(Trillion Btu),(Trillion Btu)
1,1949.0,1549.26,Not Available,1549.26,2973.98,1424.72,Not Available,Not Available,Not Available,1549.26,Not Available,Not Available,1549.26,2973.98
2,1950.0,1562.31,Not Available,1562.31,2977.72,1415.41,Not Available,Not Available,Not Available,1562.31,Not Available,Not Available,1562.31,2977.72
3,1951.0,1534.67,Not Available,1534.67,2958.46,1423.8,Not Available,Not Available,Not Available,1534.67,Not Available,Not Available,1534.67,2958.46
4,1952.0,1474.37,Not Available,1474.37,2940.18,1465.81,Not Available,Not Available,Not Available,1474.37,Not Available,Not Available,1474.37,2940.18
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67,2015.0,2311.77,2161.44,4991.58,9728.76,2321.18,211.836,426.867,1777.31,2311.77,518.371,2153.22,4983.36,9720.54
68,2016.0,2296.7,2274.95,5074.86,10422.9,2472.44,209.604,570.368,2095.59,2224.12,503.219,2287.18,5014.52,10362.5
69,2017.0,2259.19,2344.3,5098.75,11195.9,2766.97,210.233,777.084,2342.89,2180.56,495.26,2303.52,4979.34,11076.5
70,2018.0,2354.56,2396.57,5238.48,11508.4,2663.14,208.865,915.513,2482.36,2260.51,487.347,2283.25,5031.1,11301
71,2019.0,2330.28,2327.52,5100.24,11508.6,2563.23,201.269,1018.01,2625.85,2226.64,442.447,2254.72,4923.81,11332.2

In [65]:
energy_prod = energy_prod.rename(columns={'Annual Total':'Year', 'Wood Energy Production':'Wood_production', 'Biofuels Production':'Biofuel_Production',
       'Total Biomass Energy Production':'Total_Biomass_Prod', 'Total Renewable Energy Production':'Total_Renewable_Production',
       'Hydroelectric Power Consumption':'Hydro_consumption', 'Geothermal Energy Consumption':'Geo_Consumption',
       'Solar Energy Consumption':'Solar_Consumption', 'Wind Energy Consumption':'Wind_Consumption',
       'Wood Energy Consumption':'Wood_Consumption', 'Waste Energy Consumption':'WasteEnergy_Consumption',
       'Biofuels Consumption':'Biofuel_consumption', 'Total Biomass Energy Consumption':'Total_Biomass_Consumption',
       'Total Renewable Energy Consumption':'Total_Renewable_Consumption'})

In [66]:
# dropping column with all null values
energy_prod.dropna(axis =1 ,how = "all",inplace = True)

In [67]:
energy_prod.drop(index=0, inplace=True)

In [68]:
energy_prod.head()

,Year,Wood_production,Biofuel_Production,Total_Biomass_Prod,Total_Renewable_Production,Hydro_consumption,Geo_Consumption,Solar_Consumption,Wind_Consumption,Wood_Consumption,WasteEnergy_Consumption,Biofuel_consumption,Total_Biomass_Consumption,Total_Renewable_Consumption
1,1949.0,1549.26,Not Available,1549.26,2973.98,1424.72,Not Available,Not Available,Not Available,1549.26,Not Available,Not Available,1549.26,2973.98
2,1950.0,1562.31,Not Available,1562.31,2977.72,1415.41,Not Available,Not Available,Not Available,1562.31,Not Available,Not Available,1562.31,2977.72
3,1951.0,1534.67,Not Available,1534.67,2958.46,1423.8,Not Available,Not Available,Not Available,1534.67,Not Available,Not Available,1534.67,2958.46
4,1952.0,1474.37,Not Available,1474.37,2940.18,1465.81,Not Available,Not Available,Not Available,1474.37,Not Available,Not Available,1474.37,2940.18
5,1953.0,1418.6,Not Available,1418.6,2831.46,1412.86,Not Available,Not Available,Not Available,1418.6,Not Available,Not Available,1418.6,2831.46

In [69]:
energy_prod['Year'] = energy_prod['Year'].astype(int)

In [70]:
#Replace Not available with zeros
energy_prod = energy_prod.replace('Not Available', 0)

In [71]:
energy_prod.head()

,Year,Wood_production,Biofuel_Production,Total_Biomass_Prod,Total_Renewable_Production,Hydro_consumption,Geo_Consumption,Solar_Consumption,Wind_Consumption,Wood_Consumption,WasteEnergy_Consumption,Biofuel_consumption,Total_Biomass_Consumption,Total_Renewable_Consumption
1,1949,1549.262,0.0,1549.262,2973.984,1424.722,0.0,0.0,0.0,1549.262,0.0,0.0,1549.262,2973.984
2,1950,1562.307,0.0,1562.307,2977.718,1415.411,0.0,0.0,0.0,1562.307,0.0,0.0,1562.307,2977.718
3,1951,1534.669,0.0,1534.669,2958.464,1423.795,0.0,0.0,0.0,1534.669,0.0,0.0,1534.669,2958.464
4,1952,1474.369,0.0,1474.369,2940.181,1465.812,0.0,0.0,0.0,1474.369,0.0,0.0,1474.369,2940.181
5,1953,1418.601,0.0,1418.601,2831.460,1412.859,0.0,0.0,0.0,1418.601,0.0,0.0,1418.601,2831.460

In [72]:
# energy_prod.tail(30)

In [73]:
energy_cons['Total_primary_Cosumption']

1      31.967775
2      34.598567
3      36.953661
4      36.726037
5      37.640598
         ...
67     97.375221
68     97.335208
69     97.594743
70    101.161852
71    100.273806
Name: Total_primary_Cosumption, Length: 71, dtype: float64

In [74]:
#  Quadrillion                                     Trillion
energy_prod['Total_Energy_Consumption'] = energy_cons['Total_primary_Cosumption']
energy_prod

,Year,Wood_production,Biofuel_Production,Total_Biomass_Prod,Total_Renewable_Production,Hydro_consumption,Geo_Consumption,Solar_Consumption,Wind_Consumption,Wood_Consumption,WasteEnergy_Consumption,Biofuel_consumption,Total_Biomass_Consumption,Total_Renewable_Consumption,Total_Energy_Consumption
1,1949,1549.262,0.000,1549.262,2973.984,1424.722,0.000,0.000,0.000,1549.262,0.000,0.000,1549.262,2973.984,31.967775
2,1950,1562.307,0.000,1562.307,2977.718,1415.411,0.000,0.000,0.000,1562.307,0.000,0.000,1562.307,2977.718,34.598567
3,1951,1534.669,0.000,1534.669,2958.464,1423.795,0.000,0.000,0.000,1534.669,0.000,0.000,1534.669,2958.464,36.953661
4,1952,1474.369,0.000,1474.369,2940.181,1465.812,0.000,0.000,0.000,1474.369,0.000,0.000,1474.369,2940.181,36.726037
5,1953,1418.601,0.000,1418.601,2831.460,1412.859,0.000,0.000,0.000,1418.601,0.000,0.000,1418.601,2831.460,37.640598
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67,2015,2311.768,2161.440,4991.579,9728.765,2321.177,211.836,426.867,1777.306,2311.768,518.371,2153.219,4983.358,9720.544,97.375221
68,2016,2296.696,2274.948,5074.863,10422.872,2472.442,209.604,570.368,2095.595,2224.121,503.219,2287.182,5014.521,10362.530,97.335208
69,2017,2259.189,2344.298,5098.747,11195.923,2766.967,210.233,777.084,2342.891,2180.563,495.260,2303.518,4979.340,11076.515,97.594743
70,2018,2354.564,2396.573,5238.484,11508.364,2663.138,208.865,915.513,2482.364,2260.506,487.347,2283.247,5031.100,11300.980,101.161852
71,2019,2330.279,2327.517,5100.242,11508.598,2563.228,201.269,1018.013,2625.846,2226.635,442.447,2254.725,4923.807,11332.162,100.273806

In [75]:
# Convert the quadrillion to Trillion
energy_prod['Total_Energy_Consumption'] = energy_prod['Total_Energy_Consumption'] * 1000

In [76]:
energy_prod.head()

,Year,Wood_production,Biofuel_Production,Total_Biomass_Prod,Total_Renewable_Production,Hydro_consumption,Geo_Consumption,Solar_Consumption,Wind_Consumption,Wood_Consumption,WasteEnergy_Consumption,Biofuel_consumption,Total_Biomass_Consumption,Total_Renewable_Consumption,Total_Energy_Consumption
1,1949,1549.262,0.0,1549.262,2973.984,1424.722,0.0,0.0,0.0,1549.262,0.0,0.0,1549.262,2973.984,31967.775
2,1950,1562.307,0.0,1562.307,2977.718,1415.411,0.0,0.0,0.0,1562.307,0.0,0.0,1562.307,2977.718,34598.567
3,1951,1534.669,0.0,1534.669,2958.464,1423.795,0.0,0.0,0.0,1534.669,0.0,0.0,1534.669,2958.464,36953.661
4,1952,1474.369,0.0,1474.369,2940.181,1465.812,0.0,0.0,0.0,1474.369,0.0,0.0,1474.369,2940.181,36726.037
5,1953,1418.601,0.0,1418.601,2831.460,1412.859,0.0,0.0,0.0,1418.601,0.0,0.0,1418.601,2831.460,37640.598

In [77]:
energy_prod['Total_Renewable_Production_Twh'] = energy_prod['Total_Renewable_Production'] * .293071070172222
energy_prod['Total_Renewable_Consumption_Twh'] = energy_prod['Total_Renewable_Consumption'] * .293071070172222
energy_prod['Total_Energy_Consumption_Twh'] = energy_prod['Total_Energy_Consumption'] * .293071070172222

In [78]:
energy_prod

,Year,Wood_production,Biofuel_Production,Total_Biomass_Prod,Total_Renewable_Production,Hydro_consumption,Geo_Consumption,Solar_Consumption,Wind_Consumption,Wood_Consumption,WasteEnergy_Consumption,Biofuel_consumption,Total_Biomass_Consumption,Total_Renewable_Consumption,Total_Energy_Consumption,Total_Renewable_Production_Twh,Total_Renewable_Consumption_Twh,Total_Energy_Consumption_Twh
1,1949,1549.262,0.000,1549.262,2973.984,1424.722,0.000,0.000,0.000,1549.262,0.000,0.000,1549.262,2973.984,31967.775,871.588674,871.588674,9368.830030
2,1950,1562.307,0.000,1562.307,2977.718,1415.411,0.000,0.000,0.000,1562.307,0.000,0.000,1562.307,2977.718,34598.567,872.683001,872.683001,10139.839057
3,1951,1534.669,0.000,1534.669,2958.464,1423.795,0.000,0.000,0.000,1534.669,0.000,0.000,1534.669,2958.464,36953.661,867.040211,867.040211,10830.048976
4,1952,1474.369,0.000,1474.369,2940.181,1465.812,0.000,0.000,0.000,1474.369,0.000,0.000,1474.369,2940.181,36726.037,861.681992,861.681992,10763.338967
5,1953,1418.601,0.000,1418.601,2831.460,1412.859,0.000,0.000,0.000,1418.601,0.000,0.000,1418.601,2831.460,37640.598,829.819012,829.819012,11031.370338
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67,2015,2311.768,2161.440,4991.579,9728.765,2321.177,211.836,426.867,1777.306,2311.768,518.371,2153.219,4983.358,9720.544,97375.221,2851.219570,2848.810233,28537.860227
68,2016,2296.696,2274.948,5074.863,10422.872,2472.442,209.604,570.368,2095.595,2224.121,503.219,2287.182,5014.521,10362.530,97335.208,3054.642251,3036.957757,28526.133574
69,2017,2259.189,2344.298,5098.747,11195.923,2766.967,210.233,777.084,2342.891,2180.563,495.260,2303.518,4979.340,11076.515,97594.743,3281.201135,3246.206105,28602.195774
70,2018,2354.564,2396.573,5238.484,11508.364,2663.138,208.865,915.513,2482.364,2260.506,487.347,2283.247,5031.100,11300.980,101161.852,3372.768553,3311.990303,29647.612226
71,2019,2330.279,2327.517,5100.242,11508.598,2563.228,201.269,1018.013,2625.846,2226.635,442.447,2254.725,4923.807,11332.162,100273.806,3372.837132,3321.128845,29387.351635

# Connect and Update to Mongo

In [157]:
import pymongo
from pymongo import MongoClient

# conn = 'mongodb://localhost:27017'

# #     conn = f'mongodb+srv://{username}:{password}@cluster0.zdhdq.mongodb.net/{dbname}?retryWrites=true&w=majority'
# client = MongoClient(conn)

# # Define the Database in Mongo
# db = client.renewable_energy

# collection = db[collectionName]
# gdp_cons = energy_cons1.to_dict('records')
# collection.insert_many(gdp_cons)

### Energy consumption collection created in mongo

In [158]:
#Default port used by MongoDB is 27017
conn='mongodb://localhost:27017'
client=pymongo.MongoClient(conn)
#Decleare the database
db=client['renewable_energy']

In [134]:
#Declare the collection
col_engcons=db['energyconsumption']

df=energy_cons.to_dict('records')
col_engcons.insert_many(df)

In [135]:
for row in db.energyconsumption.find():
    pprint(row)
    print("------------------------")

{'Bio_Consumption': 1.549262,
 'Coal_Consumption': 11.980905,
 'Electric_consumption': 0.0,
 'Fossil_Consumption': 28.988371,
 'Gas_Consumption': 5.145142,
 'Geo_Consumption': 0.0,
 'Hydro_Consumption': 1.424722,
 'Petro_Consumption': 11.868994,
 'Solar_Consumption': 0.0,
 'Total_Renewable_Consumption': 2.973984,
 'Total_primary_Cosumption': 31.967775,
 'Wind_Consumption': 0.0,
 'Year': 1949,
 '_id': ObjectId('5fc69f45b7abff5a7656b754')}
------------------------
{'Bio_Consumption': 1.562307,
 'Coal_Consumption': 12.347109,
 'Electric_consumption': 0.0,
 'Fossil_Consumption': 31.614755,
 'Gas_Consumption': 5.968371,
 'Geo_Consumption': 0.0,
 'Hydro_Consumption': 1.415411,
 'Petro_Consumption': 13.298283,
 'Solar_Consumption': 0.0,
 'Total_Renewable_Consumption': 2.977718,
 'Total_primary_Cosumption': 34.598567,
 'Wind_Consumption': 0.0,
 'Year': 1950,
 '_id': ObjectId('5fc69f45b7abff5a7656b755')}
------------------------
{'Bio_Consumption': 1.534669,
 'Coal_Consumption': 12.552996,
 'Electric_consumption': 0.0,
 'Fossil_Consumption': 33.987736,
 'Gas_Consumption': 7.048518,
 'Geo_Consumption': 0.0,
 'Hydro_Consumption': 1.423795,
 'Petro_Consumption': 14.407674,
 'Solar_Consumption': 0.0,
 'Total_Renewable_Consumption': 2.958464,
 'Total_primary_Cosumption': 36.953661,
 'Wind_Consumption': 0.0,
 'Year': 1951,
 '_id': ObjectId('5fc69f45b7abff5a7656b756')}
------------------------
{'Bio_Consumption': 1.474369,
 'Coal_Consumption': 11.306479,
 'Electric_consumption': 0.0,
 'Fossil_Consumption': 33.778116,
 'Gas_Consumption': 7.549621,
 'Geo_Consumption': 0.0,
 'Hydro_Consumption': 1.465812,
 'Petro_Consumption': 14.933895,
 'Solar_Consumption': 0.0,
 'Total_Renewable_Consumption': 2.940181,
 'Total_primary_Cosumption': 36.726037,
 'Wind_Consumption': 0.0,
 'Year': 1952,
 '_id': ObjectId('5fc69f45b7abff5a7656b757')}
------------------------
{'Bio_Consumption': 1.418601,
 'Coal_Consumption': 11.372684,
 'Electric_consumption': 0.0,
 'Fossil_Consumption': 34.802286,
 'Gas_Consumption': 7.906645,
 'Geo_Consumption': 0.0,
 'Hydro_Consumption': 1.412859,
 'Petro_Consumption': 15.531959,
 'Solar_Consumption': 0.0,
 'Total_Renewable_Consumption': 2.83146,
 'Total_primary_Cosumption': 37.640598,
 'Wind_Consumption': 0.0,
 'Year': 1953,
 '_id': ObjectId('5fc69f45b7abff5a7656b758')}
------------------------
{'Bio_Consumption': 1.394327,
 'Coal_Consumption': 9.714667,
 'Electric_consumption': 0.0,
 'Fossil_Consumption': 33.851458,
 'Gas_Consumption': 8.330202,
 'Geo_Consumption': 0.0,
 'Hydro_Consumption': 1.359772,
 'Petro_Consumption': 15.813334,
 'Solar_Consumption': 0.0,
 'Total_Renewable_Consumption': 2.754099,
 'Total_primary_Cosumption': 36.61354,
 'Wind_Consumption': 0.0,
 'Year': 1954,
 '_id': ObjectId('5fc69f45b7abff5a7656b759')}
------------------------
{'Bio_Consumption': 1.424143,
 'Coal_Consumption': 11.167259,
 'Electric_consumption': 0.0,
 'Fossil_Consumption': 37.380419,
 'Gas_Consumption': 8.997935,
 'Geo_Consumption': 0.0,
 'Hydro_Consumption': 1.359844,
 'Petro_Consumption': 17.225269,
 'Solar_Consumption': 0.0,
 'Total_Renewable_Consumption': 2.783987,
 'Total_primary_Cosumption': 40.178285,
 'Wind_Consumption': 0.0,
 'Year': 1955,
 '_id': ObjectId('5fc69f45b7abff5a7656b75a')}
------------------------
{'Bio_Consumption': 1.415871,
 'Coal_Consumption': 11.349723,
 'Electric_consumption': 0.0,
 'Fossil_Consumption': 38.855656,
 'Gas_Consumption': 9.613975,
 'Geo_Consumption': 0.0,
 'Hydro_Consumption': 1.434711,
 'Petro_Consumption': 17.904978,
 'Solar_Consumption': 0.0,
 'Total_Renewable_Consumption': 2.850582,
 'Total_primary_Cosumption': 41.721757,
 'Wind_Consumption': 0.0,
 'Year': 1956,
 '_id': ObjectId('5fc69f45b7abff5a7656b75b')}
------------------------
{'Bio_Consumption': 1.333581,
 'Coal_Consumption': 10.820631,
 'Electric_consumption': 0.000112,
 'Fossil_Consumption': 38.892315,
 'Gas_Consumption': 10.190753,
 'Geo_Consumption': 0.0,
 'Hydro_Consumption': 1.515613,
 'Petro_Consumption': 17.89839,
 'Solar_Consumption': 0.0,
 'Total_Renewable_Consumption': 2.849194,
 'Total_primary_Cosumption': 41.753909,
 'Wind_Consumption': 0.0,
 'Year': 1957,
 '_id': ObjectId('5fc69f45b7abff5a7656b75c')}
------------------------
{'Bio_Consumption': 1.323123,
 'Coal_Consumption': 9.533287,
 'Electric_consumption': 0.001915,
 'Fossil_Consumption': 38.680955,
 'Gas_Consumption': 10.663199,
 'Geo_Consumption': 0.0,
 'Hydro_Consumption': 1.591967,
 'Petro_Consumption': 18.49119,
 'Solar_Consumption': 0.0,
 'Total_Renewable_Consumption': 2.91509,
 'Total_primary_Cosumption': 41.60928,
 'Wind_Consumption': 0.0,
 'Year': 1958,
 '_id': ObjectId('5fc69f45b7abff5a7656b75d')}
------------------------
{'Bio_Consumption': 1.352874,
 'Coal_Consumption': 9.518353,
 'Electric_consumption': 0.002187,
 'Fossil_Consumption': 40.507312,
 'Gas_Consumption': 11.717422,
 'Geo_Consumption': 0.0,
 'Hydro_Consumption': 1.548465,
 'Petro_Consumption': 19.279894,
 'Solar_Consumption': 0.0,
 'Total_Renewable_Consumption': 2.901339,
 'Total_primary_Cosumption': 43.422965,
 'Wind_Consumption': 0.0,
 'Year': 1959,
 '_id': ObjectId('5fc69f45b7abff5a7656b75e')}
------------------------
{'Bio_Consumption': 1.31987,
 'Coal_Consumption': 9.837785,
 'Electric_consumption': 0.006026,
 'Fossil_Consumption': 42.091028,
 'Gas_Consumption': 12.385366,
 'Geo_Consumption': 0.000359,
 'Hydro_Consumption': 1.607975,
 'Petro_Consumption': 19.873507,
 'Solar_Consumption': 0.0,
 'Total_Renewable_Consumption': 2.928204,
 'Total_primary_Cosumption': 45.040732,
 'Wind_Consumption': 0.0,
 'Year': 1960,
 '_id': ObjectId('5fc69f45b7abff5a7656b75f')}
------------------------
{'Bio_Consumption': 1.294762,
 'Coal_Consumption': 9.623351,
 'Electric_consumption': 0.019678,
 'Fossil_Consumption': 42.711189,
 'Gas_Consumption': 12.926392,
 'Geo_Consumption': 0.001001,
 'Hydro_Consumption': 1.656463,
 'Petro_Consumption': 20.169333,
 'Solar_Consumption': 0.0,
 'Total_Renewable_Consumption': 2.952226,
 'Total_primary_Cosumption': 45.690782,
 'Wind_Consumption': 0.0,
 'Year': 1961,
 '_id': ObjectId('5fc69f45b7abff5a7656b760')}
------------------------
{'Bio_Consumption': 1.300242,
 'Coal_Consumption': 9.906454,
 'Electric_consumption': 0.026394,
 'Fossil_Consumption': 44.62938,
 'Gas_Consumption': 13.730841,
 'Geo_Consumption': 0.001061,
 'Hydro_Consumption': 1.816141,
 'Petro_Consumption': 20.997591,
 'Solar_Consumption': 0.0,
 'Total_Renewable_Consumption': 3.117444,
 'Total_primary_Cosumption': 47.775047,
 'Wind_Consumption': 0.0,
 'Year': 1962,
 '_id': ObjectId('5fc69f45b7abff5a7656b761')}
------------------------
{'Bio_Consumption': 1.323316,
 'Coal_Consumption': 10.412538,
 'Electric_consumption': 0.038147,
 'Fossil_Consumption': 46.45372,
 'Gas_Consumption': 14.403306,
 'Geo_Consumption': 0.00176,
 'Hydro_Consumption': 1.771355,
 'Petro_Consumption': 21.645265,
 'Solar_Consumption': 0.0,
 'Total_Renewable_Consumption': 3.096431,
 'Total_primary_Cosumption': 49.588632,
 'Wind_Consumption': 0.0,
 'Year': 1963,
 '_id': ObjectId('5fc69f45b7abff5a7656b762')}
------------------------
{'Bio_Consumption': 1.336802,
 'Coal_Consumption': 10.964385,
 'Electric_consumption': 0.039819,
 'Fossil_Consumption': 48.483687,
 'Gas_Consumption': 15.28785,
 'Geo_Consumption': 0.002132,
 'Hydro_Consumption': 1.886314,
 'Petro_Consumption': 22.241894,
 'Solar_Consumption': 0.0,
 'Total_Renewable_Consumption': 3.225248,
 'Total_primary_Cosumption': 51.755425,
 'Wind_Consumption': 0.0,
 'Year': 1964,
 '_id': ObjectId('5fc69f45b7abff5a7656b763')}
------------------------
{'Bio_Consumption': 1.334761,
 'Coal_Consumption': 11.580608,
 'Electric_consumption': 0.043164,
 'Fossil_Consumption': 50.514724,
 'Gas_Consumption': 15.768667,
 'Geo_Consumption': 0.001978,
 'Hydro_Consumption': 2.059077,
 'Petro_Consumption': 23.1839,
 'Solar_Consumption': 0.0,
 'Total_Renewable_Consumption': 3.395816,
 'Total_primary_Cosumption': 53.953222,
 'Wind_Consumption': 0.0,
 'Year': 1965,
 '_id': ObjectId('5fc69f45b7abff5a7656b764')}
------------------------
{'Bio_Consumption': 1.368985,
 'Coal_Consumption': 12.14308,
 'Electric_consumption': 0.064158,
 'Fossil_Consumption': 53.448822,
 'Gas_Consumption': 16.995332,
 'Geo_Consumption': 0.001958,
 'Hydro_Consumption': 2.061519,
 'Petro_Consumption': 24.335358,
 'Solar_Consumption': 0.0,
 'Total_Renewable_Consumption': 3.432462,
 'Total_primary_Cosumption': 56.949167,
 'Wind_Consumption': 0.0,
 'Year': 1966,
 '_id': ObjectId('5fc69f45b7abff5a7656b765')}
------------------------
{'Bio_Consumption': 1.340249,
 'Coal_Consumption': 11.91375,
 'Electric_consumption': 0.088456,
 'Fossil_Consumption': 55.117171,
 'Gas_Consumption': 17.944788,
 'Geo_Consumption': 0.0033,
 'Hydro_Consumption': 2.346664,
 'Petro_Consumption': 25.273959,
 'Solar_Consumption': 0.0,
 'Total_Renewable_Consumption': 3.690213,
 'Total_primary_Cosumption': 58.89482,
 'Wind_Consumption': 0.0,
 'Year': 1967,
 '_id': ObjectId('5fc69f45b7abff5a7656b766')}
------------------------
{'Bio_Consumption': 1.419495,
 'Coal_Consumption': 12.330677,
 'Electric_consumption': 0.141534,
 'Fossil_Consumption': 58.489442,
 'Gas_Consumption': 19.209656,
 'Geo_Consumption': 0.004532,
 'Hydro_Consumption': 2.348629,
 'Petro_Consumption': 26.966419,
 'Solar_Consumption': 0.0,
 'Total_Renewable_Consumption': 3.772656,
 'Total_primary_Cosumption': 62.40148,
 'Wind_Consumption': 0.0,
 'Year': 1968,
 '_id': ObjectId('5fc69f45b7abff5a7656b767')}
------------------------
{'Bio_Consumption': 1.440487,
 'Coal_Consumption': 12.38154,
 'Electric_consumption': 0.153722,
 'Fossil_Consumption': 61.343989,
 'Gas_Consumption': 20.677984,
 'Geo_Consumption': 0.006422,
 'Hydro_Consumption': 2.647983,
 'Petro_Consumption': 28.320574,
 'Solar_Consumption': 0.0,
 'Total_Renewable_Consumption': 4.094892,
 'Total_primary_Cosumption': 65.596259,
 'Wind_Consumption': 0.0,
 'Year': 1969,
 '_id': ObjectId('5fc69f45b7abff5a7656b768')}
------------------------
{'Bio_Consumption': 1.430962,
 'Coal_Consumption': 12.264528,
 'Electric_consumption': 0.239347,
 'Fossil_Consumption': 63.500772,
 'Gas_Consumption': 21.794707,
 'Geo_Consumption': 0.005511,
 'Hydro_Consumption': 2.633547,
 'Petro_Consumption': 29.499198,
 'Solar_Consumption': 0.0,
 'Total_Renewable_Consumption': 4.070021,
 'Total_primary_Cosumption': 67.816828,
 'Wind_Consumption': 0.0,
 'Year': 1970,
 '_id': ObjectId('5fc69f45b7abff5a7656b769')}
------------------------
{'Bio_Consumption': 1.432323,
 'Coal_Consumption': 11.598411,
 'Electric_consumption': 0.412939,
 'Fossil_Consumption': 64.573073,
 'Gas_Consumption': 22.469052,
 'Geo_Consumption': 0.005739,
 'Hydro_Consumption': 2.824151,
 'Petro_Consumption': 30.538718,
 'Solar_Consumption': 0.0,
 'Total_Renewable_Consumption': 4.262213,
 'Total_primary_Cosumption': 69.260271,
 'Wind_Consumption': 0.0,
 'Year': 1971,
 '_id': ObjectId('5fc69f45b7abff5a7656b76a')}
------------------------
{'Bio_Consumption': 1.503065,
 'Coal_Consumption': 12.076917,
 'Electric_consumption': 0.583752,
 'Fossil_Consumption': 67.668048,
 'Gas_Consumption': 22.69819,
 'Geo_Consumption': 0.015079,
 'Hydro_Consumption': 2.863865,
 'Petro_Consumption': 32.918906,
 'Solar_Consumption': 0.0,
 'Total_Renewable_Consumption': 4.382009,
 'Total_primary_Cosumption': 72.660036,
 'Wind_Consumption': 0.0,
 'Year': 1972,
 '_id': ObjectId('5fc69f45b7abff5a7656b76b')}
------------------------
{'Bio_Consumption': 1.529068,
 'Coal_Consumption': 12.97149,
 'Electric_consumption': 0.910177,
 'Fossil_Consumption': 70.28245,
 'Gas_Consumption': 22.512399,
 'Geo_Consumption': 0.020422,
 'Hydro_Consumption': 2.861448,
 'Petro_Consumption': 34.806025,
 'Solar_Consumption': 0.0,
 'Total_Renewable_Consumption': 4.410938,
 'Total_primary_Cosumption': 75.65228,
 'Wind_Consumption': 0.0,
 'Year': 1973,
 '_id': ObjectId('5fc69f45b7abff5a7656b76c')}
------------------------
{'Bio_Consumption': 1.539662,
 'Coal_Consumption': 12.662878,
 'Electric_consumption': 1.272083,
 'Fossil_Consumption': 67.872076,
 'Gas_Consumption': 21.732488,
 'Geo_Consumption': 0.02561,
 'Hydro_Consumption': 3.17658,
 'Petro_Consumption': 33.420613,
 'Solar_Consumption': 0.0,
 'Total_Renewable_Consumption': 4.741852,
 'Total_primary_Cosumption': 73.929322,
 'Wind_Consumption': 0.0,
 'Year': 1974,
 '_id': ObjectId('5fc69f45b7abff5a7656b76d')}
------------------------
{'Bio_Consumption': 1.498734,
 'Coal_Consumption': 12.662786,
 'Electric_consumption': 1.899798,
 'Fossil_Consumption': 65.32299,
 'Gas_Consumption': 19.947883,
 'Geo_Consumption': 0.03378,
 'Hydro_Consumption': 3.154607,
 'Petro_Consumption': 32.698781,
 'Solar_Consumption': 0.0,
 'Total_Renewable_Consumption': 4.68712,
 'Total_primary_Cosumption': 71.931011,
 'Wind_Consumption': 0.0,
 'Year': 1975,
 '_id': ObjectId('5fc69f45b7abff5a7656b76e')}
------------------------
{'Bio_Consumption': 1.713373,
 'Coal_Consumption': 13.584067,
 'Electric_consumption': 2.111121,
 'Fossil_Consumption': 69.071379,
 'Gas_Consumption': 20.345426,
 'Geo_Consumption': 0.037513,
 'Hydro_Consumption': 2.976265,
 'Petro_Consumption': 35.141985,
 'Solar_Consumption': 0.0,
 'Total_Renewable_Consumption': 4.727151,
 'Total_primary_Cosumption': 75.939029,
 'Wind_Consumption': 0.0,
 'Year': 1976,
 '_id': ObjectId('5fc69f45b7abff5a7656b76f')}
------------------------
{'Bio_Consumption': 1.838332,
 'Coal_Consumption': 13.922103,
 'Electric_consumption': 2.701762,
 'Fossil_Consumption': 70.949841,
 'Gas_Consumption': 19.930513,
 'Geo_Consumption': 0.037382,
 'Hydro_Consumption': 2.333252,
 'Petro_Consumption': 37.082642,
 'Solar_Consumption': 0.0,
 'Total_Renewable_Consumption': 4.208966,
 'Total_primary_Cosumption': 77.919991,
 'Wind_Consumption': 0.0,
 'Year': 1977,
 '_id': ObjectId('5fc69f45b7abff5a7656b770')}
------------------------
{'Bio_Consumption': 2.037605,
 'Coal_Consumption': 13.765575,
 'Electric_consumption': 3.024126,
 'Fossil_Consumption': 71.80982,
 'Gas_Consumption': 20.0004,
 'Geo_Consumption': 0.030851,
 'Hydro_Consumption': 2.936983,
 'Petro_Consumption': 37.919119,
 'Solar_Consumption': 0.0,
 'Total_Renewable_Consumption': 5.00544,
 'Total_primary_Cosumption': 79.906703,
 'Wind_Consumption': 0.0,
 'Year': 1978,
 '_id': ObjectId('5fc69f45b7abff5a7656b771')}
------------------------
{'Bio_Consumption': 2.151906,
 'Coal_Consumption': 15.039586,
 'Electric_consumption': 2.775827,
 'Fossil_Consumption': 72.843726,
 'Gas_Consumption': 20.665817,
 'Geo_Consumption': 0.040262,
 'Hydro_Consumption': 2.930686,
 'Petro_Consumption': 37.075478,
 'Solar_Consumption': 0.0,
 'Total_Renewable_Consumption': 5.122854,
 'Total_primary_Cosumption': 80.811788,
 'Wind_Consumption': 0.0,
 'Year': 1979,
 '_id': ObjectId('5fc69f45b7abff5a7656b772')}
------------------------
{'Bio_Consumption': 2.4755,
 'Coal_Consumption': 15.422809,
 'Electric_consumption': 2.739169,
 'Fossil_Consumption': 69.782203,
 'Gas_Consumption': 20.235459,
 'Geo_Consumption': 0.052699,
 'Hydro_Consumption': 2.900144,
 'Petro_Consumption': 34.158965,
 'Solar_Consumption': 0.0,
 'Total_Renewable_Consumption': 5.428342,
 'Total_primary_Cosumption': 78.021113,
 'Wind_Consumption': 0.0,
 'Year': 1980,
 '_id': ObjectId('5fc69f45b7abff5a7656b773')}
------------------------
{'Bio_Consumption': 2.596283,
 'Coal_Consumption': 15.907526,
 'Electric_consumption': 3.007589,
 'Fossil_Consumption': 67.522504,
 'Gas_Consumption': 19.74731,
 'Geo_Consumption': 0.059437,
 'Hydro_Consumption': 2.757968,
 'Petro_Consumption': 31.883616,
 'Solar_Consumption': 0.0,
 'Total_Renewable_Consumption': 5.413688,
 'Total_primary_Cosumption': 76.057187,
 'Wind_Consumption': 0.0,
 'Year': 1981,
 '_id': ObjectId('5fc69f45b7abff5a7656b774')}
------------------------
{'Bio_Consumption': 2.663452,
 'Coal_Consumption': 15.321581,
 'Electric_consumption': 3.131148,
 'Fossil_Consumption': 63.835377,
 'Gas_Consumption': 18.356222,
 'Geo_Consumption': 0.050627,
 'Hydro_Consumption': 3.265558,
 'Petro_Consumption': 30.17923,
 'Solar_Consumption': 0.0,
 'Total_Renewable_Consumption': 5.979637,
 'Total_primary_Cosumption': 73.046189,
 'Wind_Consumption': 0.0,
 'Year': 1982,
 '_id': ObjectId('5fc69f45b7abff5a7656b775')}
------------------------
{'Bio_Consumption': 2.904414,
 'Coal_Consumption': 15.894442,
 'Electric_consumption': 3.202549,
 'Fossil_Consumption': 63.096686,
 'Gas_Consumption': 17.220836,
 'Geo_Consumption': 0.06391,
 'Hydro_Consumption': 3.52726,
 'Petro_Consumption': 29.997044,
 'Solar_Consumption': 0.0,
 'Total_Renewable_Consumption': 6.495612,
 'Total_primary_Cosumption': 72.915394,
 'Wind_Consumption': 2.8e-05,
 'Year': 1983,
 '_id': ObjectId('5fc69f45b7abff5a7656b776')}
------------------------
{'Bio_Consumption': 2.97112,
 'Coal_Consumption': 17.070622,
 'Electric_consumption': 3.552531,
 'Fossil_Consumption': 66.444979,
 'Gas_Consumption': 18.393613,
 'Geo_Consumption': 0.080811,
 'Hydro_Consumption': 3.385811,
 'Petro_Consumption': 30.992232,
 'Solar_Consumption': 5.5e-05,
 'Total_Renewable_Consumption': 6.437864,
 'Total_primary_Cosumption': 76.570697,
 'Wind_Consumption': 6.8e-05,
 'Year': 1984,
 '_id': ObjectId('5fc69f45b7abff5a7656b777')}
------------------------
{'Bio_Consumption': 3.016233,
 'Coal_Consumption': 17.478428,
 'Electric_consumption': 4.075563,
 'Fossil_Consumption': 66.0349,
 'Gas_Consumption': 17.703482,
 'Geo_Consumption': 0.097421,
 'Hydro_Consumption': 2.970192,
 'Petro_Consumption': 30.866482,
 'Solar_Consumption': 0.000111,
 'Total_Renewable_Consumption': 6.084017,
 'Total_primary_Cosumption': 76.334135,
 'Wind_Consumption': 6e-05,
 'Year': 1985,
 '_id': ObjectId('5fc69f45b7abff5a7656b778')}
------------------------
{'Bio_Consumption': 2.932095,
 'Coal_Consumption': 17.260405,
 'Electric_consumption': 4.380109,
 'Fossil_Consumption': 65.985158,
 'Gas_Consumption': 16.591364,
 'Geo_Consumption': 0.107677,
 'Hydro_Consumption': 3.071179,
 'Petro_Consumption': 32.150143,
 'Solar_Consumption': 0.000147,
 'Total_Renewable_Consumption': 6.11114,
 'Total_primary_Cosumption': 76.598888,
 'Wind_Consumption': 4.4e-05,
 'Year': 1986,
 '_id': ObjectId('5fc69f45b7abff5a7656b779')}
------------------------
{'Bio_Consumption': 2.874884,
 'Coal_Consumption': 18.008451,
 'Electric_consumption': 4.753933,
 'Fossil_Consumption': 68.474361,
 'Gas_Consumption': 17.639801,
 'Geo_Consumption': 0.11227,
 'Hydro_Consumption': 2.634508,
 'Petro_Consumption': 32.817479,
 'Solar_Consumption': 0.000109,
 'Total_Renewable_Consumption': 5.621807,
 'Total_primary_Cosumption': 79.008203,
 'Wind_Consumption': 3.7e-05,
 'Year': 1987,
 '_id': ObjectId('5fc69f45b7abff5a7656b77a')}
------------------------
{'Bio_Consumption': 3.016049,
 'Coal_Consumption': 18.846312,
 'Electric_consumption': 5.586968,
 'Fossil_Consumption': 71.507048,
 'Gas_Consumption': 18.448393,
 'Geo_Consumption': 0.106338,
 'Hydro_Consumption': 2.334265,
 'Petro_Consumption': 34.172792,
 'Solar_Consumption': 9.4e-05,
 'Total_Renewable_Consumption': 5.456754,
 'Total_primary_Cosumption': 82.659169,
 'Wind_Consumption': 9e-06,
 'Year': 1988,
 '_id': ObjectId('5fc69f45b7abff5a7656b77b')}
------------------------
{'Bio_Consumption': 3.159357,
 'Coal_Consumption': 19.069762,
 'Electric_consumption': 5.602161,
 'Fossil_Consumption': 72.865725,
 'Gas_Consumption': 19.601606,
 'Geo_Consumption': 0.161539,
 'Hydro_Consumption': 2.837263,
 'Petro_Consumption': 34.163952,
 'Solar_Consumption': 0.054466,
 'Total_Renewable_Consumption': 6.234658,
 'Total_primary_Cosumption': 84.739993,
 'Wind_Consumption': 0.022033,
 'Year': 1989,
 '_id': ObjectId('5fc69f45b7abff5a7656b77c')}
------------------------
{'Bio_Consumption': 2.735112,
 'Coal_Consumption': 19.172635,
 'Electric_consumption': 6.10435,
 'Fossil_Consumption': 72.280598,
 'Gas_Consumption': 19.603267,
 'Geo_Consumption': 0.170747,
 'Hydro_Consumption': 3.046391,
 'Petro_Consumption': 33.499918,
 'Solar_Consumption': 0.058768,
 'Total_Renewable_Consumption': 6.040024,
 'Total_primary_Cosumption': 84.43286,
 'Wind_Consumption': 0.029007,
 'Year': 1990,
 '_id': ObjectId('5fc69f45b7abff5a7656b77d')}
------------------------

In [159]:
# Energy production collection created in mongo
#Declare the collection
col_engprod=db['energyproduction']

energy_prod=energy_prod.to_dict('records')
col_engprod.insert_many(energy_prod)

In [160]:
for row in db.energyproduction.find():
    pprint(row)
    print("------------------------")

{'Biofuel_Production': 0.0,
 'Biofuel_consumption': 0.0,
 'Geo_Consumption': 0.0,
 'Hydro_consumption': 1424.722,
 'Solar_Consumption': 0.0,
 'Total_Biomass_Consumption': 1549.262,
 'Total_Biomass_Prod': 1549.262,
 'Total_Energy_Consumption': 31967.774999999998,
 'Total_Renewable_Consumption': 2973.984,
 'Total_Renewable_Production': 2973.984,
 'WasteEnergy_Consumption': 0.0,
 'Wind_Consumption': 0.0,
 'Wood_Consumption': 1549.262,
 'Wood_production': 1549.262,
 'Year': 1949,
 '_id': ObjectId('5fc6fe9bb7abff5a7656b7e3')}
------------------------
{'Biofuel_Production': 0.0,
 'Biofuel_consumption': 0.0,
 'Geo_Consumption': 0.0,
 'Hydro_consumption': 1415.411,
 'Solar_Consumption': 0.0,
 'Total_Biomass_Consumption': 1562.307,
 'Total_Biomass_Prod': 1562.307,
 'Total_Energy_Consumption': 34598.567,
 'Total_Renewable_Consumption': 2977.718,
 'Total_Renewable_Production': 2977.718,
 'WasteEnergy_Consumption': 0.0,
 'Wind_Consumption': 0.0,
 'Wood_Consumption': 1562.307,
 'Wood_production': 1562.307,
 'Year': 1950,
 '_id': ObjectId('5fc6fe9bb7abff5a7656b7e4')}
------------------------
{'Biofuel_Production': 0.0,
 'Biofuel_consumption': 0.0,
 'Geo_Consumption': 0.0,
 'Hydro_consumption': 1423.795,
 'Solar_Consumption': 0.0,
 'Total_Biomass_Consumption': 1534.669,
 'Total_Biomass_Prod': 1534.669,
 'Total_Energy_Consumption': 36953.661,
 'Total_Renewable_Consumption': 2958.464,
 'Total_Renewable_Production': 2958.464,
 'WasteEnergy_Consumption': 0.0,
 'Wind_Consumption': 0.0,
 'Wood_Consumption': 1534.669,
 'Wood_production': 1534.669,
 'Year': 1951,
 '_id': ObjectId('5fc6fe9bb7abff5a7656b7e5')}
------------------------
{'Biofuel_Production': 0.0,
 'Biofuel_consumption': 0.0,
 'Geo_Consumption': 0.0,
 'Hydro_consumption': 1465.812,
 'Solar_Consumption': 0.0,
 'Total_Biomass_Consumption': 1474.369,
 'Total_Biomass_Prod': 1474.369,
 'Total_Energy_Consumption': 36726.037,
 'Total_Renewable_Consumption': 2940.181,
 'Total_Renewable_Production': 2940.181,
 'WasteEnergy_Consumption': 0.0,
 'Wind_Consumption': 0.0,
 'Wood_Consumption': 1474.369,
 'Wood_production': 1474.369,
 'Year': 1952,
 '_id': ObjectId('5fc6fe9bb7abff5a7656b7e6')}
------------------------
{'Biofuel_Production': 0.0,
 'Biofuel_consumption': 0.0,
 'Geo_Consumption': 0.0,
 'Hydro_consumption': 1412.859,
 'Solar_Consumption': 0.0,
 'Total_Biomass_Consumption': 1418.601,
 'Total_Biomass_Prod': 1418.601,
 'Total_Energy_Consumption': 37640.598,
 'Total_Renewable_Consumption': 2831.46,
 'Total_Renewable_Production': 2831.46,
 'WasteEnergy_Consumption': 0.0,
 'Wind_Consumption': 0.0,
 'Wood_Consumption': 1418.601,
 'Wood_production': 1418.601,
 'Year': 1953,
 '_id': ObjectId('5fc6fe9bb7abff5a7656b7e7')}
------------------------
{'Biofuel_Production': 0.0,
 'Biofuel_consumption': 0.0,
 'Geo_Consumption': 0.0,
 'Hydro_consumption': 1359.772,
 'Solar_Consumption': 0.0,
 'Total_Biomass_Consumption': 1394.327,
 'Total_Biomass_Prod': 1394.327,
 'Total_Energy_Consumption': 36613.54,
 'Total_Renewable_Consumption': 2754.099,
 'Total_Renewable_Production': 2754.099,
 'WasteEnergy_Consumption': 0.0,
 'Wind_Consumption': 0.0,
 'Wood_Consumption': 1394.327,
 'Wood_production': 1394.327,
 'Year': 1954,
 '_id': ObjectId('5fc6fe9bb7abff5a7656b7e8')}
------------------------
{'Biofuel_Production': 0.0,
 'Biofuel_consumption': 0.0,
 'Geo_Consumption': 0.0,
 'Hydro_consumption': 1359.844,
 'Solar_Consumption': 0.0,
 'Total_Biomass_Consumption': 1424.143,
 'Total_Biomass_Prod': 1424.143,
 'Total_Energy_Consumption': 40178.285,
 'Total_Renewable_Consumption': 2783.987,
 'Total_Renewable_Production': 2783.987,
 'WasteEnergy_Consumption': 0.0,
 'Wind_Consumption': 0.0,
 'Wood_Consumption': 1424.143,
 'Wood_production': 1424.143,
 'Year': 1955,
 '_id': ObjectId('5fc6fe9bb7abff5a7656b7e9')}
------------------------
{'Biofuel_Production': 0.0,
 'Biofuel_consumption': 0.0,
 'Geo_Consumption': 0.0,
 'Hydro_consumption': 1434.711,
 'Solar_Consumption': 0.0,
 'Total_Biomass_Consumption': 1415.871,
 'Total_Biomass_Prod': 1415.871,
 'Total_Energy_Consumption': 41721.757,
 'Total_Renewable_Consumption': 2850.582,
 'Total_Renewable_Production': 2850.582,
 'WasteEnergy_Consumption': 0.0,
 'Wind_Consumption': 0.0,
 'Wood_Consumption': 1415.871,
 'Wood_production': 1415.871,
 'Year': 1956,
 '_id': ObjectId('5fc6fe9bb7abff5a7656b7ea')}
------------------------
{'Biofuel_Production': 0.0,
 'Biofuel_consumption': 0.0,
 'Geo_Consumption': 0.0,
 'Hydro_consumption': 1515.613,
 'Solar_Consumption': 0.0,
 'Total_Biomass_Consumption': 1333.581,
 'Total_Biomass_Prod': 1333.581,
 'Total_Energy_Consumption': 41753.909,
 'Total_Renewable_Consumption': 2849.194,
 'Total_Renewable_Production': 2849.194,
 'WasteEnergy_Consumption': 0.0,
 'Wind_Consumption': 0.0,
 'Wood_Consumption': 1333.581,
 'Wood_production': 1333.581,
 'Year': 1957,
 '_id': ObjectId('5fc6fe9bb7abff5a7656b7eb')}
------------------------
{'Biofuel_Production': 0.0,
 'Biofuel_consumption': 0.0,
 'Geo_Consumption': 0.0,
 'Hydro_consumption': 1591.967,
 'Solar_Consumption': 0.0,
 'Total_Biomass_Consumption': 1323.123,
 'Total_Biomass_Prod': 1323.123,
 'Total_Energy_Consumption': 41609.28,
 'Total_Renewable_Consumption': 2915.09,
 'Total_Renewable_Production': 2915.09,
 'WasteEnergy_Consumption': 0.0,
 'Wind_Consumption': 0.0,
 'Wood_Consumption': 1323.123,
 'Wood_production': 1323.123,
 'Year': 1958,
 '_id': ObjectId('5fc6fe9bb7abff5a7656b7ec')}
------------------------
{'Biofuel_Production': 0.0,
 'Biofuel_consumption': 0.0,
 'Geo_Consumption': 0.0,
 'Hydro_consumption': 1548.465,
 'Solar_Consumption': 0.0,
 'Total_Biomass_Consumption': 1352.874,
 'Total_Biomass_Prod': 1352.874,
 'Total_Energy_Consumption': 43422.965,
 'Total_Renewable_Consumption': 2901.339,
 'Total_Renewable_Production': 2901.339,
 'WasteEnergy_Consumption': 0.0,
 'Wind_Consumption': 0.0,
 'Wood_Consumption': 1352.874,
 'Wood_production': 1352.874,
 'Year': 1959,
 '_id': ObjectId('5fc6fe9bb7abff5a7656b7ed')}
------------------------
{'Biofuel_Production': 0.0,
 'Biofuel_consumption': 0.0,
 'Geo_Consumption': 0.359,
 'Hydro_consumption': 1607.975,
 'Solar_Consumption': 0.0,
 'Total_Biomass_Consumption': 1319.87,
 'Total_Biomass_Prod': 1319.87,
 'Total_Energy_Consumption': 45040.731999999996,
 'Total_Renewable_Consumption': 2928.204,
 'Total_Renewable_Production': 2928.204,
 'WasteEnergy_Consumption': 0.0,
 'Wind_Consumption': 0.0,
 'Wood_Consumption': 1319.87,
 'Wood_production': 1319.87,
 'Year': 1960,
 '_id': ObjectId('5fc6fe9bb7abff5a7656b7ee')}
------------------------
{'Biofuel_Production': 0.0,
 'Biofuel_consumption': 0.0,
 'Geo_Consumption': 1.001,
 'Hydro_consumption': 1656.463,
 'Solar_Consumption': 0.0,
 'Total_Biomass_Consumption': 1294.762,
 'Total_Biomass_Prod': 1294.762,
 'Total_Energy_Consumption': 45690.782,
 'Total_Renewable_Consumption': 2952.226,
 'Total_Renewable_Production': 2952.226,
 'WasteEnergy_Consumption': 0.0,
 'Wind_Consumption': 0.0,
 'Wood_Consumption': 1294.762,
 'Wood_production': 1294.762,
 'Year': 1961,
 '_id': ObjectId('5fc6fe9bb7abff5a7656b7ef')}
------------------------
{'Biofuel_Production': 0.0,
 'Biofuel_consumption': 0.0,
 'Geo_Consumption': 1.061,
 'Hydro_consumption': 1816.141,
 'Solar_Consumption': 0.0,
 'Total_Biomass_Consumption': 1300.242,
 'Total_Biomass_Prod': 1300.242,
 'Total_Energy_Consumption': 47775.047,
 'Total_Renewable_Consumption': 3117.444,
 'Total_Renewable_Production': 3117.444,
 'WasteEnergy_Consumption': 0.0,
 'Wind_Consumption': 0.0,
 'Wood_Consumption': 1300.242,
 'Wood_production': 1300.242,
 'Year': 1962,
 '_id': ObjectId('5fc6fe9bb7abff5a7656b7f0')}
------------------------
{'Biofuel_Production': 0.0,
 'Biofuel_consumption': 0.0,
 'Geo_Consumption': 1.76,
 'Hydro_consumption': 1771.355,
 'Solar_Consumption': 0.0,
 'Total_Biomass_Consumption': 1323.316,
 'Total_Biomass_Prod': 1323.316,
 'Total_Energy_Consumption': 49588.632,
 'Total_Renewable_Consumption': 3096.431,
 'Total_Renewable_Production': 3096.431,
 'WasteEnergy_Consumption': 0.0,
 'Wind_Consumption': 0.0,
 'Wood_Consumption': 1323.316,
 'Wood_production': 1323.316,
 'Year': 1963,
 '_id': ObjectId('5fc6fe9bb7abff5a7656b7f1')}
------------------------
{'Biofuel_Production': 0.0,
 'Biofuel_consumption': 0.0,
 'Geo_Consumption': 2.132,
 'Hydro_consumption': 1886.314,
 'Solar_Consumption': 0.0,
 'Total_Biomass_Consumption': 1336.802,
 'Total_Biomass_Prod': 1336.802,
 'Total_Energy_Consumption': 51755.425,
 'Total_Renewable_Consumption': 3225.248,
 'Total_Renewable_Production': 3225.248,
 'WasteEnergy_Consumption': 0.0,
 'Wind_Consumption': 0.0,
 'Wood_Consumption': 1336.802,
 'Wood_production': 1336.802,
 'Year': 1964,
 '_id': ObjectId('5fc6fe9bb7abff5a7656b7f2')}
------------------------
{'Biofuel_Production': 0.0,
 'Biofuel_consumption': 0.0,
 'Geo_Consumption': 1.978,
 'Hydro_consumption': 2059.077,
 'Solar_Consumption': 0.0,
 'Total_Biomass_Consumption': 1334.761,
 'Total_Biomass_Prod': 1334.761,
 'Total_Energy_Consumption': 53953.221999999994,
 'Total_Renewable_Consumption': 3395.816,
 'Total_Renewable_Production': 3395.816,
 'WasteEnergy_Consumption': 0.0,
 'Wind_Consumption': 0.0,
 'Wood_Consumption': 1334.761,
 'Wood_production': 1334.761,
 'Year': 1965,
 '_id': ObjectId('5fc6fe9bb7abff5a7656b7f3')}
------------------------
{'Biofuel_Production': 0.0,
 'Biofuel_consumption': 0.0,
 'Geo_Consumption': 1.958,
 'Hydro_consumption': 2061.519,
 'Solar_Consumption': 0.0,
 'Total_Biomass_Consumption': 1368.985,
 'Total_Biomass_Prod': 1368.985,
 'Total_Energy_Consumption': 56949.167,
 'Total_Renewable_Consumption': 3432.462,
 'Total_Renewable_Production': 3432.462,
 'WasteEnergy_Consumption': 0.0,
 'Wind_Consumption': 0.0,
 'Wood_Consumption': 1368.985,
 'Wood_production': 1368.985,
 'Year': 1966,
 '_id': ObjectId('5fc6fe9bb7abff5a7656b7f4')}
------------------------
{'Biofuel_Production': 0.0,
 'Biofuel_consumption': 0.0,
 'Geo_Consumption': 3.3,
 'Hydro_consumption': 2346.664,
 'Solar_Consumption': 0.0,
 'Total_Biomass_Consumption': 1340.249,
 'Total_Biomass_Prod': 1340.249,
 'Total_Energy_Consumption': 58894.82,
 'Total_Renewable_Consumption': 3690.213,
 'Total_Renewable_Production': 3690.213,
 'WasteEnergy_Consumption': 0.0,
 'Wind_Consumption': 0.0,
 'Wood_Consumption': 1340.249,
 'Wood_production': 1340.249,
 'Year': 1967,
 '_id': ObjectId('5fc6fe9bb7abff5a7656b7f5')}
------------------------
{'Biofuel_Production': 0.0,
 'Biofuel_consumption': 0.0,
 'Geo_Consumption': 4.532,
 'Hydro_consumption': 2348.629,
 'Solar_Consumption': 0.0,
 'Total_Biomass_Consumption': 1419.495,
 'Total_Biomass_Prod': 1419.495,
 'Total_Energy_Consumption': 62401.479999999996,
 'Total_Renewable_Consumption': 3772.656,
 'Total_Renewable_Production': 3772.656,
 'WasteEnergy_Consumption': 0.0,
 'Wind_Consumption': 0.0,
 'Wood_Consumption': 1419.495,
 'Wood_production': 1419.495,
 'Year': 1968,
 '_id': ObjectId('5fc6fe9bb7abff5a7656b7f6')}
------------------------
{'Biofuel_Production': 0.0,
 'Biofuel_consumption': 0.0,
 'Geo_Consumption': 6.422,
 'Hydro_consumption': 2647.983,
 'Solar_Consumption': 0.0,
 'Total_Biomass_Consumption': 1440.487,
 'Total_Biomass_Prod': 1440.487,
 'Total_Energy_Consumption': 65596.259,
 'Total_Renewable_Consumption': 4094.892,
 'Total_Renewable_Production': 4094.892,
 'WasteEnergy_Consumption': 0.0,
 'Wind_Consumption': 0.0,
 'Wood_Consumption': 1440.487,
 'Wood_production': 1440.487,
 'Year': 1969,
 '_id': ObjectId('5fc6fe9bb7abff5a7656b7f7')}
------------------------
{'Biofuel_Production': 0.0,
 'Biofuel_consumption': 0.0,
 'Geo_Consumption': 5.511,
 'Hydro_consumption': 2633.547,
 'Solar_Consumption': 0.0,
 'Total_Biomass_Consumption': 1430.962,
 'Total_Biomass_Prod': 1430.962,
 'Total_Energy_Consumption': 67816.828,
 'Total_Renewable_Consumption': 4070.021,
 'Total_Renewable_Production': 4070.021,
 'WasteEnergy_Consumption': 2.313,
 'Wind_Consumption': 0.0,
 'Wood_Consumption': 1428.649,
 'Wood_production': 1428.649,
 'Year': 1970,
 '_id': ObjectId('5fc6fe9bb7abff5a7656b7f8')}
------------------------
{'Biofuel_Production': 0.0,
 'Biofuel_consumption': 0.0,
 'Geo_Consumption': 5.739,
 'Hydro_consumption': 2824.151,
 'Solar_Consumption': 0.0,
 'Total_Biomass_Consumption': 1432.323,
 'Total_Biomass_Prod': 1432.323,
 'Total_Energy_Consumption': 69260.27100000001,
 'Total_Renewable_Consumption': 4262.213,
 'Total_Renewable_Production': 4262.213,
 'WasteEnergy_Consumption': 2.094,
 'Wind_Consumption': 0.0,
 'Wood_Consumption': 1430.229,
 'Wood_production': 1430.229,
 'Year': 1971,
 '_id': ObjectId('5fc6fe9bb7abff5a7656b7f9')}
------------------------
{'Biofuel_Production': 0.0,
 'Biofuel_consumption': 0.0,
 'Geo_Consumption': 15.079,
 'Hydro_consumption': 2863.865,
 'Solar_Consumption': 0.0,
 'Total_Biomass_Consumption': 1503.065,
 'Total_Biomass_Prod': 1503.065,
 'Total_Energy_Consumption': 72660.03600000001,
 'Total_Renewable_Consumption': 4382.009,
 'Total_Renewable_Production': 4382.009,
 'WasteEnergy_Consumption': 2.073,
 'Wind_Consumption': 0.0,
 'Wood_Consumption': 1500.992,
 'Wood_production': 1500.992,
 'Year': 1972,
 '_id': ObjectId('5fc6fe9bb7abff5a7656b7fa')}
------------------------
{'Biofuel_Production': 0.0,
 'Biofuel_consumption': 0.0,
 'Geo_Consumption': 20.422,
 'Hydro_consumption': 2861.448,
 'Solar_Consumption': 0.0,
 'Total_Biomass_Consumption': 1529.068,
 'Total_Biomass_Prod': 1529.068,
 'Total_Energy_Consumption': 75652.28,
 'Total_Renewable_Consumption': 4410.938,
 'Total_Renewable_Production': 4410.938,
 'WasteEnergy_Consumption': 2.056,
 'Wind_Consumption': 0.0,
 'Wood_Consumption': 1527.012,
 'Wood_production': 1527.012,
 'Year': 1973,
 '_id': ObjectId('5fc6fe9bb7abff5a7656b7fb')}
------------------------
{'Biofuel_Production': 0.0,
 'Biofuel_consumption': 0.0,
 'Geo_Consumption': 25.61,
 'Hydro_consumption': 3176.58,
 'Solar_Consumption': 0.0,
 'Total_Biomass_Consumption': 1539.662,
 'Total_Biomass_Prod': 1539.662,
 'Total_Energy_Consumption': 73929.322,
 'Total_Renewable_Consumption': 4741.852,
 'Total_Renewable_Production': 4741.852,
 'WasteEnergy_Consumption': 1.902,
 'Wind_Consumption': 0.0,
 'Wood_Consumption': 1537.76,
 'Wood_production': 1537.76,
 'Year': 1974,
 '_id': ObjectId('5fc6fe9bb7abff5a7656b7fc')}
------------------------
{'Biofuel_Production': 0.0,
 'Biofuel_consumption': 0.0,
 'Geo_Consumption': 33.78,
 'Hydro_consumption': 3154.607,
 'Solar_Consumption': 0.0,
 'Total_Biomass_Consumption': 1498.734,
 'Total_Biomass_Prod': 1498.734,
 'Total_Energy_Consumption': 71931.011,
 'Total_Renewable_Consumption': 4687.12,
 'Total_Renewable_Production': 4687.12,
 'WasteEnergy_Consumption': 1.806,
 'Wind_Consumption': 0.0,
 'Wood_Consumption': 1496.928,
 'Wood_production': 1496.928,
 'Year': 1975,
 '_id': ObjectId('5fc6fe9bb7abff5a7656b7fd')}
------------------------
{'Biofuel_Production': 0.0,
 'Biofuel_consumption': 0.0,
 'Geo_Consumption': 37.513,
 'Hydro_consumption': 2976.265,
 'Solar_Consumption': 0.0,
 'Total_Biomass_Consumption': 1713.373,
 'Total_Biomass_Prod': 1713.373,
 'Total_Energy_Consumption': 75939.02900000001,
 'Total_Renewable_Consumption': 4727.151,
 'Total_Renewable_Production': 4727.151,
 'WasteEnergy_Consumption': 1.889,
 'Wind_Consumption': 0.0,
 'Wood_Consumption': 1711.484,
 'Wood_production': 1711.484,
 'Year': 1976,
 '_id': ObjectId('5fc6fe9bb7abff5a7656b7fe')}
------------------------
{'Biofuel_Production': 0.0,
 'Biofuel_consumption': 0.0,
 'Geo_Consumption': 37.382,
 'Hydro_consumption': 2333.252,
 'Solar_Consumption': 0.0,
 'Total_Biomass_Consumption': 1838.332,
 'Total_Biomass_Prod': 1838.332,
 'Total_Energy_Consumption': 77919.991,
 'Total_Renewable_Consumption': 4208.966,
 'Total_Renewable_Production': 4208.966,
 'WasteEnergy_Consumption': 1.808,
 'Wind_Consumption': 0.0,
 'Wood_Consumption': 1836.524,
 'Wood_production': 1836.524,
 'Year': 1977,
 '_id': ObjectId('5fc6fe9bb7abff5a7656b7ff')}
------------------------
{'Biofuel_Production': 0.0,
 'Biofuel_consumption': 0.0,
 'Geo_Consumption': 30.851,
 'Hydro_consumption': 2936.983,
 'Solar_Consumption': 0.0,
 'Total_Biomass_Consumption': 2037.605,
 'Total_Biomass_Prod': 2037.605,
 'Total_Energy_Consumption': 79906.703,
 'Total_Renewable_Consumption': 5005.44,
 'Total_Renewable_Production': 5005.44,
 'WasteEnergy_Consumption': 1.455,
 'Wind_Consumption': 0.0,
 'Wood_Consumption': 2036.15,
 'Wood_production': 2036.15,
 'Year': 1978,
 '_id': ObjectId('5fc6fe9bb7abff5a7656b800')}
------------------------
{'Biofuel_Production': 0.0,
 'Biofuel_consumption': 0.0,
 'Geo_Consumption': 40.262,
 'Hydro_consumption': 2930.686,
 'Solar_Consumption': 0.0,
 'Total_Biomass_Consumption': 2151.906,
 'Total_Biomass_Prod': 2151.906,
 'Total_Energy_Consumption': 80811.788,
 'Total_Renewable_Consumption': 5122.854,
 'Total_Renewable_Production': 5122.854,
 'WasteEnergy_Consumption': 2.052,
 'Wind_Consumption': 0.0,
 'Wood_Consumption': 2149.854,
 'Wood_production': 2149.854,
 'Year': 1979,
 '_id': ObjectId('5fc6fe9bb7abff5a7656b801')}
------------------------
{'Biofuel_Production': 0.0,
 'Biofuel_consumption': 0.0,
 'Geo_Consumption': 52.699,
 'Hydro_consumption': 2900.144,
 'Solar_Consumption': 0.0,
 'Total_Biomass_Consumption': 2475.5,
 'Total_Biomass_Prod': 2475.5,
 'Total_Energy_Consumption': 78021.113,
 'Total_Renewable_Consumption': 5428.342,
 'Total_Renewable_Production': 5428.342,
 'WasteEnergy_Consumption': 1.639,
 'Wind_Consumption': 0.0,
 'Wood_Consumption': 2473.861,
 'Wood_production': 2473.861,
 'Year': 1980,
 '_id': ObjectId('5fc6fe9bb7abff5a7656b802')}
------------------------
{'Biofuel_Production': 12.72,
 'Biofuel_consumption': 12.72,
 'Geo_Consumption': 59.437,
 'Hydro_consumption': 2757.968,
 'Solar_Consumption': 0.0,
 'Total_Biomass_Consumption': 2596.283,
 'Total_Biomass_Prod': 2596.283,
 'Total_Energy_Consumption': 76057.187,
 'Total_Renewable_Consumption': 5413.688,
 'Total_Renewable_Production': 5413.688,
 'WasteEnergy_Consumption': 88.0,
 'Wind_Consumption': 0.0,
 'Wood_Consumption': 2495.563,
 'Wood_production': 2495.563,
 'Year': 1981,
 '_id': ObjectId('5fc6fe9bb7abff5a7656b803')}
------------------------
{'Biofuel_Production': 34.404,
 'Biofuel_consumption': 34.404,
 'Geo_Consumption': 50.627,
 'Hydro_consumption': 3265.558,
 'Solar_Consumption': 0.0,
 'Total_Biomass_Consumption': 2663.452,
 'Total_Biomass_Prod': 2663.452,
 'Total_Energy_Consumption': 73046.189,
 'Total_Renewable_Consumption': 5979.637,
 'Total_Renewable_Production': 5979.637,
 'WasteEnergy_Consumption': 119.0,
 'Wind_Consumption': 0.0,
 'Wood_Consumption': 2510.048,
 'Wood_production': 2510.048,
 'Year': 1982,
 '_id': ObjectId('5fc6fe9bb7abff5a7656b804')}
------------------------
{'Biofuel_Production': 63.143,
 'Biofuel_consumption': 63.143,
 'Geo_Consumption': 63.91,
 'Hydro_consumption': 3527.26,
 'Solar_Consumption': 0.0,
 'Total_Biomass_Consumption': 2904.414,
 'Total_Biomass_Prod': 2904.414,
 'Total_Energy_Consumption': 72915.394,
 'Total_Renewable_Consumption': 6495.612,
 'Total_Renewable_Production': 6495.612,
 'WasteEnergy_Consumption': 157.0,
 'Wind_Consumption': 0.028,
 'Wood_Consumption': 2684.271,
 'Wood_production': 2684.271,
 'Year': 1983,
 '_id': ObjectId('5fc6fe9bb7abff5a7656b805')}
------------------------
{'Biofuel_Production': 77.302,
 'Biofuel_consumption': 77.302,
 'Geo_Consumption': 80.811,
 'Hydro_consumption': 3385.811,
 'Solar_Consumption': 0.055,
 'Total_Biomass_Consumption': 2971.12,
 'Total_Biomass_Prod': 2971.12,
 'Total_Energy_Consumption': 76570.697,
 'Total_Renewable_Consumption': 6437.864,
 'Total_Renewable_Production': 6437.864,
 'WasteEnergy_Consumption': 208.0,
 'Wind_Consumption': 0.068,
 'Wood_Consumption': 2685.817,
 'Wood_production': 2685.817,
 'Year': 1984,
 '_id': ObjectId('5fc6fe9bb7abff5a7656b806')}
------------------------
{'Biofuel_Production': 93.151,
 'Biofuel_consumption': 93.151,
 'Geo_Consumption': 97.421,
 'Hydro_consumption': 2970.192,
 'Solar_Consumption': 0.111,
 'Total_Biomass_Consumption': 3016.233,
 'Total_Biomass_Prod': 3016.233,
 'Total_Energy_Consumption': 76334.13500000001,

In [66]:
# save the population data frame into the mongo cloud
#Declare the collection
col_population=db['Populationdata']

pop_data=pop_df.to_dict('records')
col_population.insert_many(pop_data)

In [88]:
col_uspop = db["USPopulation"]
col_uspop.insert_many(us_pop.to_dict('records'))

In [67]:
for row in db.Populationdata.find():
    pprint(row)
    print("------------------------")

{'Population': 4780125,
 'State': 'Alabama',
 'Year': 'EST2010',
 '_id': ObjectId('5fc6955bb7abff5a7656b50c')}
------------------------
{'Population': 710249,
 'State': 'Alaska',
 'Year': 'EST2010',
 '_id': ObjectId('5fc6955bb7abff5a7656b50d')}
------------------------
{'Population': 6392288,
 'State': 'Arizona',
 'Year': 'EST2010',
 '_id': ObjectId('5fc6955bb7abff5a7656b50e')}
------------------------
{'Population': 2916031,
 'State': 'Arkansas',
 'Year': 'EST2010',
 '_id': ObjectId('5fc6955bb7abff5a7656b50f')}
------------------------
{'Population': 37254519,
 'State': 'California',
 'Year': 'EST2010',
 '_id': ObjectId('5fc6955bb7abff5a7656b510')}
------------------------
{'Population': 5029319,
 'State': 'Colorado',
 'Year': 'EST2010',
 '_id': ObjectId('5fc6955bb7abff5a7656b511')}
------------------------
{'Population': 3574147,
 'State': 'Connecticut',
 'Year': 'EST2010',
 '_id': ObjectId('5fc6955bb7abff5a7656b512')}
------------------------
{'Population': 897937,
 'State': 'Delaware',
 'Year': 'EST2010',
 '_id': ObjectId('5fc6955bb7abff5a7656b513')}
------------------------
{'Population': 601767,
 'State': 'District of Columbia',
 'Year': 'EST2010',
 '_id': ObjectId('5fc6955bb7abff5a7656b514')}
------------------------
{'Population': 18804564,
 'State': 'Florida',
 'Year': 'EST2010',
 '_id': ObjectId('5fc6955bb7abff5a7656b515')}
------------------------
{'Population': 9688729,
 'State': 'Georgia',
 'Year': 'EST2010',
 '_id': ObjectId('5fc6955bb7abff5a7656b516')}
------------------------
{'Population': 1360307,
 'State': 'Hawaii',
 'Year': 'EST2010',
 '_id': ObjectId('5fc6955bb7abff5a7656b517')}
------------------------
{'Population': 1567657,
 'State': 'Idaho',
 'Year': 'EST2010',
 '_id': ObjectId('5fc6955bb7abff5a7656b518')}
------------------------
{'Population': 12831572,
 'State': 'Illinois',
 'Year': 'EST2010',
 '_id': ObjectId('5fc6955bb7abff5a7656b519')}
------------------------
{'Population': 6484051,
 'State': 'Indiana',
 'Year': 'EST2010',
 '_id': ObjectId('5fc6955bb7abff5a7656b51a')}
------------------------
{'Population': 3046871,
 'State': 'Iowa',
 'Year': 'EST2010',
 '_id': ObjectId('5fc6955bb7abff5a7656b51b')}
------------------------
{'Population': 2853123,
 'State': 'Kansas',
 'Year': 'EST2010',
 '_id': ObjectId('5fc6955bb7abff5a7656b51c')}
------------------------
{'Population': 4339333,
 'State': 'Kentucky',
 'Year': 'EST2010',
 '_id': ObjectId('5fc6955bb7abff5a7656b51d')}
------------------------
{'Population': 4533487,
 'State': 'Louisiana',
 'Year': 'EST2010',
 '_id': ObjectId('5fc6955bb7abff5a7656b51e')}
------------------------
{'Population': 1328358,
 'State': 'Maine',
 'Year': 'EST2010',
 '_id': ObjectId('5fc6955bb7abff5a7656b51f')}
------------------------
{'Population': 5773794,
 'State': 'Maryland',
 'Year': 'EST2010',
 '_id': ObjectId('5fc6955bb7abff5a7656b520')}
------------------------
{'Population': 6547785,
 'State': 'Massachusetts',
 'Year': 'EST2010',
 '_id': ObjectId('5fc6955bb7abff5a7656b521')}
------------------------
{'Population': 9884116,
 'State': 'Michigan',
 'Year': 'EST2010',
 '_id': ObjectId('5fc6955bb7abff5a7656b522')}
------------------------
{'Population': 5303927,
 'State': 'Minnesota',
 'Year': 'EST2010',
 '_id': ObjectId('5fc6955bb7abff5a7656b523')}
------------------------
{'Population': 2968130,
 'State': 'Mississippi',
 'Year': 'EST2010',
 '_id': ObjectId('5fc6955bb7abff5a7656b524')}
------------------------
{'Population': 5988950,
 'State': 'Missouri',
 'Year': 'EST2010',
 '_id': ObjectId('5fc6955bb7abff5a7656b525')}
------------------------
{'Population': 989407,
 'State': 'Montana',
 'Year': 'EST2010',
 '_id': ObjectId('5fc6955bb7abff5a7656b526')}
------------------------
{'Population': 1826305,
 'State': 'Nebraska',
 'Year': 'EST2010',
 '_id': ObjectId('5fc6955bb7abff5a7656b527')}
------------------------
{'Population': 2700677,
 'State': 'Nevada',
 'Year': 'EST2010',
 '_id': ObjectId('5fc6955bb7abff5a7656b528')}
------------------------
{'Population': 1316462,
 'State': 'New Hampshire',
 'Year': 'EST2010',
 '_id': ObjectId('5fc6955bb7abff5a7656b529')}
------------------------
{'Population': 8791978,
 'State': 'New Jersey',
 'Year': 'EST2010',
 '_id': ObjectId('5fc6955bb7abff5a7656b52a')}
------------------------
{'Population': 2059199,
 'State': 'New Mexico',
 'Year': 'EST2010',
 '_id': ObjectId('5fc6955bb7abff5a7656b52b')}
------------------------
{'Population': 19378144,
 'State': 'New York',
 'Year': 'EST2010',
 '_id': ObjectId('5fc6955bb7abff5a7656b52c')}
------------------------
{'Population': 9535751,
 'State': 'North Carolina',
 'Year': 'EST2010',
 '_id': ObjectId('5fc6955bb7abff5a7656b52d')}
------------------------
{'Population': 672576,
 'State': 'North Dakota',
 'Year': 'EST2010',
 '_id': ObjectId('5fc6955bb7abff5a7656b52e')}
------------------------
{'Population': 11536751,
 'State': 'Ohio',
 'Year': 'EST2010',
 '_id': ObjectId('5fc6955bb7abff5a7656b52f')}
------------------------
{'Population': 3751582,
 'State': 'Oklahoma',
 'Year': 'EST2010',
 '_id': ObjectId('5fc6955bb7abff5a7656b530')}
------------------------
{'Population': 3831079,
 'State': 'Oregon',
 'Year': 'EST2010',
 '_id': ObjectId('5fc6955bb7abff5a7656b531')}
------------------------
{'Population': 12702868,
 'State': 'Pennsylvania',
 'Year': 'EST2010',
 '_id': ObjectId('5fc6955bb7abff5a7656b532')}
------------------------
{'Population': 1052964,
 'State': 'Rhode Island',
 'Year': 'EST2010',
 '_id': ObjectId('5fc6955bb7abff5a7656b533')}
------------------------
{'Population': 4625366,
 'State': 'South Carolina',
 'Year': 'EST2010',
 '_id': ObjectId('5fc6955bb7abff5a7656b534')}
------------------------
{'Population': 814198,
 'State': 'South Dakota',
 'Year': 'EST2010',
 '_id': ObjectId('5fc6955bb7abff5a7656b535')}
------------------------
{'Population': 6346276,
 'State': 'Tennessee',
 'Year': 'EST2010',
 '_id': ObjectId('5fc6955bb7abff5a7656b536')}
------------------------
{'Population': 25146091,
 'State': 'Texas',
 'Year': 'EST2010',
 '_id': ObjectId('5fc6955bb7abff5a7656b537')}
------------------------
{'Population': 2763891,
 'State': 'Utah',
 'Year': 'EST2010',
 '_id': ObjectId('5fc6955bb7abff5a7656b538')}
------------------------
{'Population': 625737,
 'State': 'Vermont',
 'Year': 'EST2010',
 '_id': ObjectId('5fc6955bb7abff5a7656b539')}
------------------------
{'Population': 8001049,
 'State': 'Virginia',
 'Year': 'EST2010',
 '_id': ObjectId('5fc6955bb7abff5a7656b53a')}
------------------------
{'Population': 6724540,
 'State': 'Washington',
 'Year': 'EST2010',
 '_id': ObjectId('5fc6955bb7abff5a7656b53b')}
------------------------
{'Population': 1853018,
 'State': 'West Virginia',
 'Year': 'EST2010',
 '_id': ObjectId('5fc6955bb7abff5a7656b53c')}
------------------------
{'Population': 5687285,
 'State': 'Wisconsin',
 'Year': 'EST2010',
 '_id': ObjectId('5fc6955bb7abff5a7656b53d')}
------------------------
{'Population': 563775,
 'State': 'Wyoming',
 'Year': 'EST2010',
 '_id': ObjectId('5fc6955bb7abff5a7656b53e')}
------------------------
{'Population': 3726157,
 'State': 'Puerto Rico',
 'Year': 'EST2010',
 '_id': ObjectId('5fc6955bb7abff5a7656b53f')}
------------------------
{'Population': 4785437,
 'State': 'Alabama',
 'Year': '2010',
 '_id': ObjectId('5fc6955bb7abff5a7656b540')}
------------------------
{'Population': 713910,
 'State': 'Alaska',
 'Year': '2010',
 '_id': ObjectId('5fc6955bb7abff5a7656b541')}
------------------------
{'Population': 6407172,
 'State': 'Arizona',
 'Year': '2010',
 '_id': ObjectId('5fc6955bb7abff5a7656b542')}
------------------------
{'Population': 2921964,
 'State': 'Arkansas',
 'Year': '2010',
 '_id': ObjectId('5fc6955bb7abff5a7656b543')}
------------------------
{'Population': 37319502,
 'State': 'California',
 'Year': '2010',
 '_id': ObjectId('5fc6955bb7abff5a7656b544')}
------------------------
{'Population': 5047349,
 'State': 'Colorado',
 'Year': '2010',
 '_id': ObjectId('5fc6955bb7abff5a7656b545')}
------------------------
{'Population': 3579114,
 'State': 'Connecticut',
 'Year': '2010',
 '_id': ObjectId('5fc6955bb7abff5a7656b546')}
------------------------
{'Population': 899593,
 'State': 'Delaware',
 'Year': '2010',
 '_id': ObjectId('5fc6955bb7abff5a7656b547')}
------------------------
{'Population': 605226,
 'State': 'District of Columbia',
 'Year': '2010',
 '_id': ObjectId('5fc6955bb7abff5a7656b548')}
------------------------
{'Population': 18845537,
 'State': 'Florida',
 'Year': '2010',
 '_id': ObjectId('5fc6955bb7abff5a7656b549')}
------------------------
{'Population': 9711881,
 'State': 'Georgia',
 'Year': '2010',
 '_id': ObjectId('5fc6955bb7abff5a7656b54a')}
------------------------
{'Population': 1363963,
 'State': 'Hawaii',
 'Year': '2010',
 '_id': ObjectId('5fc6955bb7abff5a7656b54b')}
------------------------
{'Population': 1570746,
 'State': 'Idaho',
 'Year': '2010',
 '_id': ObjectId('5fc6955bb7abff5a7656b54c')}
------------------------
{'Population': 12840503,
 'State': 'Illinois',
 'Year': '2010',
 '_id': ObjectId('5fc6955bb7abff5a7656b54d')}
------------------------
{'Population': 6490432,
 'State': 'Indiana',
 'Year': '2010',
 '_id': ObjectId('5fc6955bb7abff5a7656b54e')}
------------------------
{'Population': 3050745,
 'State': 'Iowa',
 'Year': '2010',
 '_id': ObjectId('5fc6955bb7abff5a7656b54f')}
------------------------
{'Population': 2858190,
 'State': 'Kansas',
 'Year': '2010',
 '_id': ObjectId('5fc6955bb7abff5a7656b550')}
------------------------
{'Population': 4348181,
 'State': 'Kentucky',
 'Year': '2010',
 '_id': ObjectId('5fc6955bb7abff5a7656b551')}
------------------------
{'Population': 4544532,
 'State': 'Louisiana',
 'Year': '2010',
 '_id': ObjectId('5fc6955bb7abff5a7656b552')}
------------------------
{'Population': 1327629,
 'State': 'Maine',
 'Year': '2010',
 '_id': ObjectId('5fc6955bb7abff5a7656b553')}
------------------------
{'Population': 5788645,
 'State': 'Maryland',
 'Year': '2010',
 '_id': ObjectId('5fc6955bb7abff5a7656b554')}
------------------------
{'Population': 6566307,
 'State': 'Massachusetts',
 'Year': '2010',
 '_id': ObjectId('5fc6955bb7abff5a7656b555')}
------------------------
{'Population': 9877510,
 'State': 'Michigan',
 'Year': '2010',
 '_id': ObjectId('5fc6955bb7abff5a7656b556')}
------------------------
{'Population': 5310828,
 'State': 'Minnesota',
 'Year': '2010',
 '_id': ObjectId('5fc6955bb7abff5a7656b557')}
------------------------
{'Population': 2970548,
 'State': 'Mississippi',
 'Year': '2010',
 '_id': ObjectId('5fc6955bb7abff5a7656b558')}
------------------------
{'Population': 5995974,
 'State': 'Missouri',
 'Year': '2010',
 '_id': ObjectId('5fc6955bb7abff5a7656b559')}
------------------------
{'Population': 990697,
 'State': 'Montana',
 'Year': '2010',
 '_id': ObjectId('5fc6955bb7abff5a7656b55a')}
------------------------
{'Population': 1829542,
 'State': 'Nebraska',
 'Year': '2010',
 '_id': ObjectId('5fc6955bb7abff5a7656b55b')}
------------------------
{'Population': 2702405,
 'State': 'Nevada',
 'Year': '2010',
 '_id': ObjectId('5fc6955bb7abff5a7656b55c')}
------------------------
{'Population': 1316762,
 'State': 'New Hampshire',
 'Year': '2010',
 '_id': ObjectId('5fc6955bb7abff5a7656b55d')}
------------------------
{'Population': 8799446,
 'State': 'New Jersey',
 'Year': '2010',
 '_id': ObjectId('5fc6955bb7abff5a7656b55e')}
------------------------
{'Population': 2064552,
 'State': 'New Mexico',
 'Year': '2010',
 '_id': ObjectId('5fc6955bb7abff5a7656b55f')}
------------------------
{'Population': 19399878,
 'State': 'New York',
 'Year': '2010',
 '_id': ObjectId('5fc6955bb7abff5a7656b560')}
------------------------
{'Population': 9574323,
 'State': 'North Carolina',
 'Year': '2010',
 '_id': ObjectId('5fc6955bb7abff5a7656b561')}
------------------------
{'Population': 674715,
 'State': 'North Dakota',
 'Year': '2010',
 '_id': ObjectId('5fc6955bb7abff5a7656b562')}
------------------------
{'Population': 11539336,
 'State': 'Ohio',
 'Year': '2010',
 '_id': ObjectId('5fc6955bb7abff5a7656b563')}
------------------------
{'Population': 3759944,
 'State': 'Oklahoma',
 'Year': '2010',
 '_id': ObjectId('5fc6955bb7abff5a7656b564')}
------------------------
{'Population': 3837491,
 'State': 'Oregon',
 'Year': '2010',
 '_id': ObjectId('5fc6955bb7abff5a7656b565')}
------------------------
{'Population': 12711160,
 'State': 'Pennsylvania',
 'Year': '2010',
 '_id': ObjectId('5fc6955bb7abff5a7656b566')}
------------------------
{'Population': 1053959,
 'State': 'Rhode Island',
 'Year': '2010',
 '_id': ObjectId('5fc6955bb7abff5a7656b567')}
------------------------
{'Population': 4635649,
 'State': 'South Carolina',
 'Year': '2010',
 '_id': ObjectId('5fc6955bb7abff5a7656b568')}
------------------------
{'Population': 816166,
 'State': 'South Dakota',
 'Year': '2010',
 '_id': ObjectId('5fc6955bb7abff5a7656b569')}
------------------------
{'Population': 6355311,
 'State': 'Tennessee',
 'Year': '2010',
 '_id': ObjectId('5fc6955bb7abff5a7656b56a')}
------------------------
{'Population': 25241971,
 'State': 'Texas',
 'Year': '2010',
 '_id': ObjectId('5fc6955bb7abff5a7656b56b')}
------------------------
{'Population': 2775332,
 'State': 'Utah',
 'Year': '2010',
 '_id': ObjectId('5fc6955bb7abff5a7656b56c')}
------------------------
{'Population': 625879,
 'State': 'Vermont',
 'Year': '2010',
 '_id': ObjectId('5fc6955bb7abff5a7656b56d')}
------------------------
{'Population': 8023699,
 'State': 'Virginia',
 'Year': '2010',
 '_id': ObjectId('5fc6955bb7abff5a7656b56e')}
------------------------
{'Population': 6742830,
 'State': 'Washington',
 'Year': '2010',
 '_id': ObjectId('5fc6955bb7abff5a7656b56f')}
------------------------
{'Population': 1854239,
 'State': 'West Virginia',
 'Year': '2010',
 '_id': ObjectId('5fc6955bb7abff5a7656b570')}
------------------------
{'Population': 5690475,
 'State': 'Wisconsin',
 'Year': '2010',
 '_id': ObjectId('5fc6955bb7abff5a7656b571')}
------------------------
{'Population': 564487,
 'State': 'Wyoming',
 'Year': '2010',
 '_id': ObjectId('5fc6955bb7abff5a7656b572')}
------------------------
{'Population': 3721525,
 'State': 'Puerto Rico',
 'Year': '2010',
 '_id': ObjectId('5fc6955bb7abff5a7656b573')}
------------------------
{'Population': 4799069,
 'State': 'Alabama',
 'Year': '2011',
 '_id': ObjectId('5fc6955bb7abff5a7656b574')}
------------------------
{'Population': 722128,
 'State': 'Alaska',
 'Year': '2011',
 '_id': ObjectId('5fc6955bb7abff5a7656b575')}
------------------------
{'Population': 6472643,
 'State': 'Arizona',
 'Year': '2011',
 '_id': ObjectId('5fc6955bb7abff5a7656b576')}
------------------------
{'Population': 2940667,
 'State': 'Arkansas',
 'Year': '2011',
 '_id': ObjectId('5fc6955bb7abff5a7656b577')}
------------------------
{'Population': 37638369,
 'State': 'California',
 'Year': '2011',
 '_id': ObjectId('5fc6955bb7abff5a7656b578')}
------------------------
{'Population': 5121108,
 'State': 'Colorado',
 'Year': '2011',
 '_id': ObjectId('5fc6955bb7abff5a7656b579')}
------------------------
{'Population': 3588283,
 'State': 'Connecticut',
 'Year': '2011',
 '_id': ObjectId('5fc6955bb7abff5a7656b57a')}
------------------------
{'Population': 907381,
 'State': 'Delaware',
 'Year': '2011',
 '_id': ObjectId('5fc6955bb7abff5a7656b57b')}
------------------------
{'Population': 619800,
 'State': 'District of Columbia',
 'Year': '2011',
 '_id': ObjectId('5fc6955bb7abff5a7656b57c')}
------------------------
{'Population': 19053237,
 'State': 'Florida',
 'Year': '2011',
 '_id': ObjectId('5fc6955bb7abff5a7656b57d')}
------------------------
{'Population': 9802431,
 'State': 'Georgia',
 'Year': '2011',
 '_id': ObjectId('5fc6955bb7abff5a7656b57e')}
------------------------
{'Population': 1379329,
 'State': 'Hawaii',
 'Year': '2011',
 '_id': ObjectId('5fc6955bb7abff5a7656b57f')}
------------------------
{'Population': 1583910,
 'State': 'Idaho',
 'Year': '2011',
 '_id': ObjectId('5fc6955bb7abff5a7656b580')}
------------------------
{'Population': 12867454,
 'State': 'Illinois',
 'Year': '2011',
 '_id': ObjectId('5fc6955bb7abff5a7656b581')}
------------------------
{'Population': 6516528,
 'State': 'Indiana',
 'Year': '2011',
 '_id': ObjectId('5fc6955bb7abff5a7656b582')}
------------------------
{'Population': 3066336,
 'State': 'Iowa',
 'Year': '2011',
 '_id': ObjectId('5fc6955bb7abff5a7656b583')}
------------------------
{'Population': 2869225,
 'State': 'Kansas',
 'Year': '2011',
 '_id': ObjectId('5fc6955bb7abff5a7656b584')}
------------------------
{'Population': 4369821,
 'State': 'Kentucky',
 'Year': '2011',
 '_id': ObjectId('5fc6955bb7abff5a7656b585')}
------------------------
{'Population': 4575625,
 'State': 'Louisiana',
 'Year': '2011',
 '_id': ObjectId('5fc6955bb7abff5a7656b586')}
------------------------
{'Population': 1328284,
 'State': 'Maine',
 'Year': '2011',
 '_id': ObjectId('5fc6955bb7abff5a7656b587')}
------------------------
{'Population': 5839419,
 'State': 'Maryland',
 'Year': '2011',
 '_id': ObjectId('5fc6955bb7abff5a7656b588')}
------------------------
{'Population': 6613583,
 'State': 'Massachusetts',
 'Year': '2011',
 '_id': ObjectId('5fc6955bb7abff5a7656b589')}
------------------------
{'Population': 9882412,
 'State': 'Michigan',
 'Year': '2011',
 '_id': ObjectId('5fc6955bb7abff5a7656b58a')}
------------------------
{'Population': 5346143,
 'State': 'Minnesota',
 'Year': '2011',
 '_id': ObjectId('5fc6955bb7abff5a7656b58b')}
------------------------
{'Population': 2978731,
 'State': 'Mississippi',
 'Year': '2011',
 '_id': ObjectId('5fc6955bb7abff5a7656b58c')}
------------------------
{'Population': 6010275,
 'State': 'Missouri',
 'Year': '2011',
 '_id': ObjectId('5fc6955bb7abff5a7656b58d')}
------------------------
{'Population': 997316,
 'State': 'Montana',
 'Year': '2011',
 '_id': ObjectId('5fc6955bb7abff5a7656b58e')}
------------------------
{'Population': 1840672,
 'State': 'Nebraska',
 'Year': '2011',
 '_id': ObjectId('5fc6955bb7abff5a7656b58f')}
------------------------
{'Population': 2712730,
 'State': 'Nevada',
 'Year': '2011',
 '_id': ObjectId('5fc6955bb7abff5a7656b590')}
------------------------
{'Population': 1320202,
 'State': 'New Hampshire',
 'Year': '2011',
 '_id': ObjectId('5fc6955bb7abff5a7656b591')}
------------------------
{'Population': 8828117,
 'State': 'New Jersey',
 'Year': '2011',
 '_id': ObjectId('5fc6955bb7abff5a7656b592')}
------------------------
{'Population': 2080450,
 'State': 'New Mexico',
 'Year': '2011',
 '_id': ObjectId('5fc6955bb7abff5a7656b593')}
------------------------
{'Population': 19499241,
 'State': 'New York',
 'Year': '2011',
 '_id': ObjectId('5fc6955bb7abff5a7656b594')}
------------------------
{'Population': 9657592,
 'State': 'North Carolina',
 'Year': '2011',
 '_id': ObjectId('5fc6955bb7abff5a7656b595')}
------------------------
{'Population': 685225,
 'State': 'North Dakota',
 'Year': '2011',
 '_id': ObjectId('5fc6955bb7abff5a7656b596')}
------------------------
{'Population': 11544663,
 'State': 'Ohio',
 'Year': '2011',
 '_id': ObjectId('5fc6955bb7abff5a7656b597')}
------------------------
{'Population': 3788379,
 'State': 'Oklahoma',
 'Year': '2011',
 '_id': ObjectId('5fc6955bb7abff5a7656b598')}
------------------------
{'Population': 3872036,
 'State': 'Oregon',
 'Year': '2011',
 '_id': ObjectId('5fc6955bb7abff5a7656b599')}
------------------------
{'Population': 12745815,
 'State': 'Pennsylvania',
 'Year': '2011',
 '_id': ObjectId('5fc6955bb7abff5a7656b59a')}
------------------------
{'Population': 1053649,
 'State': 'Rhode Island',
 'Year': '2011',
 '_id': ObjectId('5fc6955bb7abff5a7656b59b')}
------------------------
{'Population': 4671994,
 'State': 'South Carolina',
 'Year': '2011',
 '_id': ObjectId('5fc6955bb7abff5a7656b59c')}
------------------------
{'Population': 823579,
 'State': 'South Dakota',
 'Year': '2011',
 '_id': ObjectId('5fc6955bb7abff5a7656b59d')}
------------------------
{'Population': 6399291,
 'State': 'Tennessee',
 'Year': '2011',
 '_id': ObjectId('5fc6955bb7abff5a7656b59e')}
------------------------
{'Population': 25645629,

{'Population': 10178447,
 'State': 'Georgia',
 'Year': '2015',
 '_id': ObjectId('5fc6955bb7abff5a7656b64e')}
------------------------
{'Population': 1422052,
 'State': 'Hawaii',
 'Year': '2015',
 '_id': ObjectId('5fc6955bb7abff5a7656b64f')}
------------------------
{'Population': 1651059,
 'State': 'Idaho',
 'Year': '2015',
 '_id': ObjectId('5fc6955bb7abff5a7656b650')}
------------------------
{'Population': 12858913,
 'State': 'Illinois',
 'Year': '2015',
 '_id': ObjectId('5fc6955bb7abff5a7656b651')}
------------------------
{'Population': 6608422,
 'State': 'Indiana',
 'Year': '2015',
 '_id': ObjectId('5fc6955bb7abff5a7656b652')}
------------------------
{'Population': 3120960,
 'State': 'Iowa',
 'Year': '2015',
 '_id': ObjectId('5fc6955bb7abff5a7656b653')}
------------------------
{'Population': 2909011,
 'State': 'Kansas',
 'Year': '2015',
 '_id': ObjectId('5fc6955bb7abff5a7656b654')}
------------------------
{'Population': 4425976,
 'State': 'Kentucky',
 'Year': '2015',
 '_id': ObjectId('5fc6955bb7abff5a7656b655')}
------------------------
{'Population': 4664628,
 'State': 'Louisiana',
 'Year': '2015',
 '_id': ObjectId('5fc6955bb7abff5a7656b656')}
------------------------
{'Population': 1328262,
 'State': 'Maine',
 'Year': '2015',
 '_id': ObjectId('5fc6955bb7abff5a7656b657')}
------------------------
{'Population': 5985562,
 'State': 'Maryland',
 'Year': '2015',
 '_id': ObjectId('5fc6955bb7abff5a7656b658')}
------------------------
{'Population': 6794228,
 'State': 'Massachusetts',
 'Year': '2015',
 '_id': ObjectId('5fc6955bb7abff5a7656b659')}
------------------------
{'Population': 9931715,
 'State': 'Michigan',
 'Year': '2015',
 '_id': ObjectId('5fc6955bb7abff5a7656b65a')}
------------------------
{'Population': 5482032,
 'State': 'Minnesota',
 'Year': '2015',
 '_id': ObjectId('5fc6955bb7abff5a7656b65b')}
------------------------
{'Population': 2988471,
 'State': 'Mississippi',
 'Year': '2015',
 '_id': ObjectId('5fc6955bb7abff5a7656b65c')}
------------------------
{'Population': 6071732,
 'State': 'Missouri',
 'Year': '2015',
 '_id': ObjectId('5fc6955bb7abff5a7656b65d')}
------------------------
{'Population': 1030475,
 'State': 'Montana',
 'Year': '2015',
 '_id': ObjectId('5fc6955bb7abff5a7656b65e')}
------------------------
{'Population': 1891277,
 'State': 'Nebraska',
 'Year': '2015',
 '_id': ObjectId('5fc6955bb7abff5a7656b65f')}
------------------------
{'Population': 2866939,
 'State': 'Nevada',
 'Year': '2015',
 '_id': ObjectId('5fc6955bb7abff5a7656b660')}
------------------------
{'Population': 1336350,
 'State': 'New Hampshire',
 'Year': '2015',
 '_id': ObjectId('5fc6955bb7abff5a7656b661')}
------------------------
{'Population': 8867949,
 'State': 'New Jersey',
 'Year': '2015',
 '_id': ObjectId('5fc6955bb7abff5a7656b662')}
------------------------
{'Population': 2089291,
 'State': 'New Mexico',
 'Year': '2015',
 '_id': ObjectId('5fc6955bb7abff5a7656b663')}
------------------------
{'Population': 19654666,
 'State': 'New York',
 'Year': '2015',
 '_id': ObjectId('5fc6955bb7abff5a7656b664')}
------------------------
{'Population': 10031646,
 'State': 'North Carolina',
 'Year': '2015',
 '_id': ObjectId('5fc6955bb7abff5a7656b665')}
------------------------
{'Population': 754066,
 'State': 'North Dakota',
 'Year': '2015',
 '_id': ObjectId('5fc6955bb7abff5a7656b666')}
------------------------
{'Population': 11617527,
 'State': 'Ohio',
 'Year': '2015',
 '_id': ObjectId('5fc6955bb7abff5a7656b667')}
------------------------
{'Population': 3909500,
 'State': 'Oklahoma',
 'Year': '2015',
 '_id': ObjectId('5fc6955bb7abff5a7656b668')}
------------------------
{'Population': 4015792,
 'State': 'Oregon',
 'Year': '2015',
 '_id': ObjectId('5fc6955bb7abff5a7656b669')}
------------------------
{'Population': 12784826,
 'State': 'Pennsylvania',
 'Year': '2015',
 '_id': ObjectId('5fc6955bb7abff5a7656b66a')}
------------------------
{'Population': 1056065,
 'State': 'Rhode Island',
 'Year': '2015',
 '_id': ObjectId('5fc6955bb7abff5a7656b66b')}
------------------------
{'Population': 4891938,
 'State': 'South Carolina',
 'Year': '2015',
 '_id': ObjectId('5fc6955bb7abff5a7656b66c')}
------------------------
{'Population': 853988,
 'State': 'South Dakota',
 'Year': '2015',
 '_id': ObjectId('5fc6955bb7abff5a7656b66d')}
------------------------
{'Population': 6591170,
 'State': 'Tennessee',
 'Year': '2015',
 '_id': ObjectId('5fc6955bb7abff5a7656b66e')}
------------------------
{'Population': 27470056,
 'State': 'Texas',
 'Year': '2015',
 '_id': ObjectId('5fc6955bb7abff5a7656b66f')}
------------------------
{'Population': 2981835,
 'State': 'Utah',
 'Year': '2015',
 '_id': ObjectId('5fc6955bb7abff5a7656b670')}
------------------------
{'Population': 625216,
 'State': 'Vermont',
 'Year': '2015',
 '_id': ObjectId('5fc6955bb7abff5a7656b671')}
------------------------
{'Population': 8361808,
 'State': 'Virginia',
 'Year': '2015',
 '_id': ObjectId('5fc6955bb7abff5a7656b672')}
------------------------
{'Population': 7163657,
 'State': 'Washington',
 'Year': '2015',
 '_id': ObjectId('5fc6955bb7abff5a7656b673')}
------------------------
{'Population': 1842050,
 'State': 'West Virginia',
 'Year': '2015',
 '_id': ObjectId('5fc6955bb7abff5a7656b674')}
------------------------
{'Population': 5760940,
 'State': 'Wisconsin',
 'Year': '2015',
 '_id': ObjectId('5fc6955bb7abff5a7656b675')}
------------------------
{'Population': 585613,
 'State': 'Wyoming',
 'Year': '2015',
 '_id': ObjectId('5fc6955bb7abff5a7656b676')}
------------------------
{'Population': 3473232,
 'State': 'Puerto Rico',
 'Year': '2015',
 '_id': ObjectId('5fc6955bb7abff5a7656b677')}
------------------------
{'Population': 4863525,
 'State': 'Alabama',
 'Year': '2016',
 '_id': ObjectId('5fc6955bb7abff5a7656b678')}
------------------------
{'Population': 741456,
 'State': 'Alaska',
 'Year': '2016',
 '_id': ObjectId('5fc6955bb7abff5a7656b679')}
------------------------
{'Population': 6941072,
 'State': 'Arizona',
 'Year': '2016',
 '_id': ObjectId('5fc6955bb7abff5a7656b67a')}
------------------------
{'Population': 2989918,
 'State': 'Arkansas',
 'Year': '2016',
 '_id': ObjectId('5fc6955bb7abff5a7656b67b')}
------------------------
{'Population': 39167117,
 'State': 'California',
 'Year': '2016',
 '_id': ObjectId('5fc6955bb7abff5a7656b67c')}
------------------------
{'Population': 5539215,
 'State': 'Colorado',
 'Year': '2016',
 '_id': ObjectId('5fc6955bb7abff5a7656b67d')}
------------------------
{'Population': 3578141,
 'State': 'Connecticut',
 'Year': '2016',
 '_id': ObjectId('5fc6955bb7abff5a7656b67e')}
------------------------
{'Population': 948921,
 'State': 'Delaware',
 'Year': '2016',
 '_id': ObjectId('5fc6955bb7abff5a7656b67f')}
------------------------
{'Population': 685815,
 'State': 'District of Columbia',
 'Year': '2016',
 '_id': ObjectId('5fc6955bb7abff5a7656b680')}
------------------------
{'Population': 20613477,
 'State': 'Florida',
 'Year': '2016',
 '_id': ObjectId('5fc6955bb7abff5a7656b681')}
------------------------
{'Population': 10301890,
 'State': 'Georgia',
 'Year': '2016',
 '_id': ObjectId('5fc6955bb7abff5a7656b682')}
------------------------
{'Population': 1427559,
 'State': 'Hawaii',
 'Year': '2016',
 '_id': ObjectId('5fc6955bb7abff5a7656b683')}
------------------------
{'Population': 1682380,
 'State': 'Idaho',
 'Year': '2016',
 '_id': ObjectId('5fc6955bb7abff5a7656b684')}
------------------------
{'Population': 12820527,
 'State': 'Illinois',
 'Year': '2016',
 '_id': ObjectId('5fc6955bb7abff5a7656b685')}
------------------------
{'Population': 6634304,
 'State': 'Indiana',
 'Year': '2016',
 '_id': ObjectId('5fc6955bb7abff5a7656b686')}
------------------------
{'Population': 3131371,
 'State': 'Iowa',
 'Year': '2016',
 '_id': ObjectId('5fc6955bb7abff5a7656b687')}
------------------------
{'Population': 2910844,
 'State': 'Kansas',
 'Year': '2016',
 '_id': ObjectId('5fc6955bb7abff5a7656b688')}
------------------------
{'Population': 4438182,
 'State': 'Kentucky',
 'Year': '2016',
 '_id': ObjectId('5fc6955bb7abff5a7656b689')}
------------------------
{'Population': 4678135,
 'State': 'Louisiana',
 'Year': '2016',
 '_id': ObjectId('5fc6955bb7abff5a7656b68a')}
------------------------
{'Population': 1331317,
 'State': 'Maine',
 'Year': '2016',
 '_id': ObjectId('5fc6955bb7abff5a7656b68b')}
------------------------
{'Population': 6003323,
 'State': 'Maryland',
 'Year': '2016',
 '_id': ObjectId('5fc6955bb7abff5a7656b68c')}
------------------------
{'Population': 6823608,
 'State': 'Massachusetts',
 'Year': '2016',
 '_id': ObjectId('5fc6955bb7abff5a7656b68d')}
------------------------
{'Population': 9950571,
 'State': 'Michigan',
 'Year': '2016',
 '_id': ObjectId('5fc6955bb7abff5a7656b68e')}
------------------------
{'Population': 5522744,
 'State': 'Minnesota',
 'Year': '2016',
 '_id': ObjectId('5fc6955bb7abff5a7656b68f')}
------------------------
{'Population': 2987938,
 'State': 'Mississippi',
 'Year': '2016',
 '_id': ObjectId('5fc6955bb7abff5a7656b690')}
------------------------
{'Population': 6087135,
 'State': 'Missouri',
 'Year': '2016',
 '_id': ObjectId('5fc6955bb7abff5a7656b691')}
------------------------
{'Population': 1040859,
 'State': 'Montana',
 'Year': '2016',
 '_id': ObjectId('5fc6955bb7abff5a7656b692')}
------------------------
{'Population': 1905616,
 'State': 'Nebraska',
 'Year': '2016',
 '_id': ObjectId('5fc6955bb7abff5a7656b693')}
------------------------
{'Population': 2917563,
 'State': 'Nevada',
 'Year': '2016',
 '_id': ObjectId('5fc6955bb7abff5a7656b694')}
------------------------
{'Population': 1342307,
 'State': 'New Hampshire',
 'Year': '2016',
 '_id': ObjectId('5fc6955bb7abff5a7656b695')}
------------------------
{'Population': 8870827,
 'State': 'New Jersey',
 'Year': '2016',
 '_id': ObjectId('5fc6955bb7abff5a7656b696')}
------------------------
{'Population': 2091630,
 'State': 'New Mexico',
 'Year': '2016',
 '_id': ObjectId('5fc6955bb7abff5a7656b697')}
------------------------
{'Population': 19633428,
 'State': 'New York',
 'Year': '2016',
 '_id': ObjectId('5fc6955bb7abff5a7656b698')}
------------------------
{'Population': 10154788,
 'State': 'North Carolina',
 'Year': '2016',
 '_id': ObjectId('5fc6955bb7abff5a7656b699')}
------------------------
{'Population': 754434,
 'State': 'North Dakota',
 'Year': '2016',
 '_id': ObjectId('5fc6955bb7abff5a7656b69a')}
------------------------
{'Population': 11634370,
 'State': 'Ohio',
 'Year': '2016',
 '_id': ObjectId('5fc6955bb7abff5a7656b69b')}
------------------------
{'Population': 3926331,
 'State': 'Oklahoma',
 'Year': '2016',
 '_id': ObjectId('5fc6955bb7abff5a7656b69c')}
------------------------
{'Population': 4089976,
 'State': 'Oregon',
 'Year': '2016',
 '_id': ObjectId('5fc6955bb7abff5a7656b69d')}
------------------------
{'Population': 12782275,
 'State': 'Pennsylvania',
 'Year': '2016',
 '_id': ObjectId('5fc6955bb7abff5a7656b69e')}
------------------------
{'Population': 1056770,
 'State': 'Rhode Island',
 'Year': '2016',
 '_id': ObjectId('5fc6955bb7abff5a7656b69f')}
------------------------
{'Population': 4957968,
 'State': 'South Carolina',
 'Year': '2016',
 '_id': ObjectId('5fc6955bb7abff5a7656b6a0')}
------------------------
{'Population': 862996,
 'State': 'South Dakota',
 'Year': '2016',
 '_id': ObjectId('5fc6955bb7abff5a7656b6a1')}
------------------------
{'Population': 6646010,
 'State': 'Tennessee',
 'Year': '2016',
 '_id': ObjectId('5fc6955bb7abff5a7656b6a2')}
------------------------
{'Population': 27914410,
 'State': 'Texas',
 'Year': '2016',
 '_id': ObjectId('5fc6955bb7abff5a7656b6a3')}
------------------------
{'Population': 3041868,
 'State': 'Utah',
 'Year': '2016',
 '_id': ObjectId('5fc6955bb7abff5a7656b6a4')}
------------------------
{'Population': 623657,
 'State': 'Vermont',
 'Year': '2016',
 '_id': ObjectId('5fc6955bb7abff5a7656b6a5')}
------------------------
{'Population': 8410106,
 'State': 'Virginia',
 'Year': '2016',
 '_id': ObjectId('5fc6955bb7abff5a7656b6a6')}
------------------------
{'Population': 7294771,
 'State': 'Washington',
 'Year': '2016',
 '_id': ObjectId('5fc6955bb7abff5a7656b6a7')}
------------------------
{'Population': 1831023,
 'State': 'West Virginia',
 'Year': '2016',
 '_id': ObjectId('5fc6955bb7abff5a7656b6a8')}
------------------------
{'Population': 5772628,
 'State': 'Wisconsin',
 'Year': '2016',
 '_id': ObjectId('5fc6955bb7abff5a7656b6a9')}
------------------------
{'Population': 584215,
 'State': 'Wyoming',
 'Year': '2016',
 '_id': ObjectId('5fc6955bb7abff5a7656b6aa')}
------------------------
{'Population': 3406672,
 'State': 'Puerto Rico',
 'Year': '2016',
 '_id': ObjectId('5fc6955bb7abff5a7656b6ab')}
------------------------
{'Population': 4874486,
 'State': 'Alabama',
 'Year': '2017',
 '_id': ObjectId('5fc6955bb7abff5a7656b6ac')}
------------------------
{'Population': 739700,
 'State': 'Alaska',
 'Year': '2017',
 '_id': ObjectId('5fc6955bb7abff5a7656b6ad')}
------------------------
{'Population': 7044008,
 'State': 'Arizona',
 'Year': '2017',
 '_id': ObjectId('5fc6955bb7abff5a7656b6ae')}
------------------------
{'Population': 3001345,
 'State': 'Arkansas',
 'Year': '2017',
 '_id': ObjectId('5fc6955bb7abff5a7656b6af')}
------------------------
{'Population': 39358497,
 'State': 'California',
 'Year': '2017',
 '_id': ObjectId('5fc6955bb7abff5a7656b6b0')}
------------------------
{'Population': 5611885,
 'State': 'Colorado',
 'Year': '2017',
 '_id': ObjectId('5fc6955bb7abff5a7656b6b1')}
------------------------
{'Population': 3573297,
 'State': 'Connecticut',
 'Year': '2017',
 '_id': ObjectId('5fc6955bb7abff5a7656b6b2')}
------------------------
{'Population': 956823,
 'State': 'Delaware',
 'Year': '2017',
 '_id': ObjectId('5fc6955bb7abff5a7656b6b3')}
------------------------
{'Population': 694906,
 'State': 'District of Columbia',
 'Year': '2017',
 '_id': ObjectId('5fc6955bb7abff5a7656b6b4')}
------------------------
{'Population': 20963613,
 'State': 'Florida',
 'Year': '2017',
 '_id': ObjectId('5fc6955bb7abff5a7656b6b5')}
------------------------
{'Population': 10410330,
 'State': 'Georgia',
 'Year': '2017',
 '_id': ObjectId('5fc6955bb7abff5a7656b6b6')}
------------------------
{'Population': 1424393,
 'State': 'Hawaii',
 'Year': '2017',
 '_id': ObjectId('5fc6955bb7abff5a7656b6b7')}
------------------------
{'Population': 1717715,
 'State': 'Idaho',
 'Year': '2017',
 '_id': ObjectId('5fc6955bb7abff5a7656b6b8')}
------------------------
{'Population': 12778828,
 'State': 'Illinois',
 'Year': '2017',
 '_id': ObjectId('5fc6955bb7abff5a7656b6b9')}
------------------------
{'Population': 6658078,
 'State': 'Indiana',
 'Year': '2017',
 '_id': ObjectId('5fc6955bb7abff5a7656b6ba')}
------------------------
{'Population': 3141550,
 'State': 'Iowa',
 'Year': '2017',
 '_id': ObjectId('5fc6955bb7abff5a7656b6bb')}
------------------------
{'Population': 2908718,
 'State': 'Kansas',
 'Year': '2017',
 '_id': ObjectId('5fc6955bb7abff5a7656b6bc')}
------------------------
{'Population': 4452268,
 'State': 'Kentucky',
 'Year': '2017',
 '_id': ObjectId('5fc6955bb7abff5a7656b6bd')}
------------------------
{'Population': 4670560,
 'State': 'Louisiana',
 'Year': '2017',
 '_id': ObjectId('5fc6955bb7abff5a7656b6be')}
------------------------
{'Population': 1334612,
 'State': 'Maine',
 'Year': '2017',
 '_id': ObjectId('5fc6955bb7abff5a7656b6bf')}
------------------------
{'Population': 6023868,
 'State': 'Maryland',
 'Year': '2017',
 '_id': ObjectId('5fc6955bb7abff5a7656b6c0')}
------------------------
{'Population': 6859789,
 'State': 'Massachusetts',
 'Year': '2017',
 '_id': ObjectId('5fc6955bb7abff5a7656b6c1')}
------------------------
{'Population': 9973114,
 'State': 'Michigan',
 'Year': '2017',
 '_id': ObjectId('5fc6955bb7abff5a7656b6c2')}
------------------------
{'Population': 5566230,
 'State': 'Minnesota',
 'Year': '2017',
 '_id': ObjectId('5fc6955bb7abff5a7656b6c3')}
------------------------
{'Population': 2988510,
 'State': 'Mississippi',
 'Year': '2017',
 '_id': ObjectId('5fc6955bb7abff5a7656b6c4')}
------------------------
{'Population': 6106670,
 'State': 'Missouri',
 'Year': '2017',
 '_id': ObjectId('5fc6955bb7abff5a7656b6c5')}
------------------------
{'Population': 1052482,
 'State': 'Montana',
 'Year': '2017',
 '_id': ObjectId('5fc6955bb7abff5a7656b6c6')}
------------------------
{'Population': 1915947,
 'State': 'Nebraska',
 'Year': '2017',
 '_id': ObjectId('5fc6955bb7abff5a7656b6c7')}
------------------------
{'Population': 2969905,
 'State': 'Nevada',
 'Year': '2017',
 '_id': ObjectId('5fc6955bb7abff5a7656b6c8')}
------------------------
{'Population': 1348787,
 'State': 'New Hampshire',
 'Year': '2017',
 '_id': ObjectId('5fc6955bb7abff5a7656b6c9')}
------------------------
{'Population': 8885525,
 'State': 'New Jersey',
 'Year': '2017',
 '_id': ObjectId('5fc6955bb7abff5a7656b6ca')}
------------------------
{'Population': 2091784,
 'State': 'New Mexico',
 'Year': '2017',
 '_id': ObjectId('5fc6955bb7abff5a7656b6cb')}
------------------------
{'Population': 19589572,
 'State': 'New York',
 'Year': '2017',
 '_id': ObjectId('5fc6955bb7abff5a7656b6cc')}
------------------------
{'Population': 10268233,
 'State': 'North Carolina',
 'Year': '2017',
 '_id': ObjectId('5fc6955bb7abff5a7656b6cd')}
------------------------
{'Population': 754942,
 'State': 'North Dakota',
 'Year': '2017',
 '_id': ObjectId('5fc6955bb7abff5a7656b6ce')}
------------------------
{'Population': 11659650,
 'State': 'Ohio',
 'Year': '2017',
 '_id': ObjectId('5fc6955bb7abff5a7656b6cf')}
------------------------
{'Population': 3931316,
 'State': 'Oklahoma',
 'Year': '2017',
 '_id': ObjectId('5fc6955bb7abff5a7656b6d0')}
------------------------
{'Population': 4143625,
 'State': 'Oregon',
 'Year': '2017',
 '_id': ObjectId('5fc6955bb7abff5a7656b6d1')}
------------------------
{'Population': 12787641,
 'State': 'Pennsylvania',
 'Year': '2017',
 '_id': ObjectId('5fc6955bb7abff5a7656b6d2')}
------------------------
{'Population': 1055673,
 'State': 'Rhode Island',
 'Year': '2017',
 '_id': ObjectId('5fc6955bb7abff5a7656b6d3')}
------------------------
{'Population': 5021268,
 'State': 'South Carolina',
 'Year': '2017',
 '_id': ObjectId('5fc6955bb7abff5a7656b6d4')}
------------------------
{'Population': 872868,
 'State': 'South Dakota',
 'Year': '2017',
 '_id': ObjectId('5fc6955bb7abff5a7656b6d5')}
------------------------
{'Population': 6708799,
 'State': 'Tennessee',
 'Year': '2017',
 '_id': ObjectId('5fc6955bb7abff5a7656b6d6')}
------------------------
{'Population': 28295273,
 'State': 'Texas',
 'Year': '2017',
 '_id': ObjectId('5fc6955bb7abff5a7656b6d7')}
------------------------
{'Population': 3101042,
 'State': 'Utah',
 'Year': '2017',
 '_id': ObjectId('5fc6955bb7abff5a7656b6d8')}
------------------------
{'Population': 624344,
 'State': 'Vermont',
 'Year': '2017',
 '_id': ObjectId('5fc6955bb7abff5a7656b6d9')}
------------------------
{'Population': 8463587,
 'State': 'Virginia',
 'Year': '2017',
 '_id': ObjectId('5fc6955bb7abff5a7656b6da')}
------------------------
{'Population': 7423362,
 'State': 'Washington',
 'Year': '2017',
 '_id': ObjectId('5fc6955bb7abff5a7656b6db')}
------------------------
{'Population': 1817004,
 'State': 'West Virginia',
 'Year': '2017',
 '_id': ObjectId('5fc6955bb7abff5a7656b6dc')}
------------------------
{'Population': 5790186,
 'State': 'Wisconsin',
 'Year': '2017',
 '_id': ObjectId('5fc6955bb7abff5a7656b6dd')}
------------------------
{'Population': 578931,
 'State': 'Wyoming',
 'Year': '2017',
 '_id': ObjectId('5fc6955bb7abff5a7656b6de')}
------------------------
{'Population': 3325286,
 'State': 'Puerto Rico',
 'Year': '2017',
 '_id': ObjectId('5fc6955bb7abff5a7656b6df')}
------------------------
{'Population': 4887681,
 'State': 'Alabama',
 'Year': '2018',
 '_id': ObjectId('5fc6955bb7abff5a7656b6e0')}
------------------------
{'Population': 735139,
 'State': 'Alaska',
 'Year': '2018',
 '_id': ObjectId('5fc6955bb7abff5a7656b6e1')}
------------------------
{'Population': 7158024,
 'State': 'Arizona',
 'Year': '2018',